DNNCommunity/Dnn.CommunityForums

CustomControls/UserControls/TopicView.cs
See https://github.com/ActiveForums/ActiveForums/pull/456
=> Add https://github.com/ActiveForums/ActiveForums/pull/456

class/Utilities.cs
see https://github.com/ActiveForums/ActiveForums/pull/457
=> Added https://github.com/ActiveForums/ActiveForums/pull/457

.gitignore
Added "themes/.gitignore" to the central GitIgnore file so you can have custom themes in the Themes folder without them showing up as changed files
#21 
Close #
=> fixes #21 Ignore .gitignore file in the Themes folder

App_LocalResources/ControlPanel.ascx.nl-NL.resx, App_LocalResources/Messages.ascx.nl-NL.resx, App_LocalResources/SharedResources.nl-NL.resx, App_LocalResources/WhatsNew.ascx.nl-NL.resx
Dutch resx files
- Item 1
- Item 2
- [ x] Feature solution
No issue to close
=> Dutch language pack for forum user facing user interface

BuildScripts/ModulePackage.targets
=> Resolves issue #34

ActiveForums.csproj, ActiveForums.dnn, ActiveForums_Symbols.dnn, Properties/AssemblyInfo.cs, ReleaseNotes.txt
Getting ready for the 06.04.01 release
=> Prep for 06.04.01 release

App_LocalResources/ControlPanel.ascx.nl-NL.resx
Localization keys fixed in nl-NL
- [x ] Feature solution
Close #41
=> nl-NL lanuage pack issues, fixes #41

App_LocalResources/SharedResources.nl-NL.resx, App_LocalResources/SharedResources.resx, controls/af_grid.ascx, controls/af_grid.ascx.cs
This PR the localization issue #43 is fixed.
- removed hard coded texts from .ascx file
- removed unused resourcekey attributes from .ascx file
- added code in Load to give the items the correct localized texts
- also fixed a "todo" where "Today" and "Yesterday" where not localized
- [X ] Fixes Bug
Close #43
=> fixed localization issue #43

ActiveForums.dnn, ActiveForums_Symbols.dnn, BuildScripts/ModulePackage.targets, Module.build, Properties/AssemblyInfo.cs, ReleaseNotes.txt
=> Final release tasks for 06.05.01

sql/07.00.00.SqlDataProvider
- modify stored procedure activeforums_Subscriptions_Subscribers 
Close #122
=> modify stored procedure activeforums_Subscriptions_Subscribers exclude (soft-)deleted subscribers

ActiveForums.dnn, ActiveForums_Symbols.dnn, Properties/AssemblyInfo.cs
This PR performs some minor updates to prepare for the 7.0 beta release.
=> Tasks/release prep 6.7.0

ReleaseNotes.txt
Release notes updated for v7,0.
=> Release notes updated for v7.0.

ReleaseNotes.txt
Added missing updates to release notes
=> Added missing updates to release notes

ReleaseNotes.txt
=> Updated release notes

ActiveForums.dnn, ActiveForums_Symbols.dnn, Properties/AssemblyInfo.cs, ReleaseNotes.txt
Versioning and whatnot for the next release
=> 7.0.1 Release Prep

Classic.ascx.cs
the #, it will show the issues with that number -->
Close #183
=> remove hard-coded copyright from classic forums

ActiveForums.dnn, ReleaseNotes.txt
- Made whitespace consistent in the DNN manifest  
- Added missing tasks to the release notes
=> Updated release files

ActiveForums.dnn, ActiveForums_Symbols.dnn, BuildScripts/ModulePackage.targets, ReleaseNotes.txt
Preparing for the 7.0.3 RC1 release
=> Tasks/release 7.0.3 prep

CustomControls/ServerControls/QuickReply.cs, class/Utilities.cs, controls/af_post.ascx.cs, controls/af_quickreply.ascx.cs
Enhance flood control to be ignored for superusers, admins, trusted forum users, and users with moderator privileges.
- Consolidated flood control logic, and enhanced it to bypass for admins, superusers, trusted forum users, and users with forum moderator privileges.
Close #95
=> Enhance flood control

CustomControls/UserControls/TopicView.cs, config/tokens.config
Adds _lock_ and _pin_ actions to the Topic view, so you don't need to navigate to a different view, or open the topic itself.
Close #153
=> Add 'Lock' and 'Pin' actions to TopicView

ActiveForums.dnn, ReleaseNotes.txt
- Updated release notes  
- Updated manifest
=> Version 07.00.05 release prep

controls/admin_manageforums_forumeditor.ascx
move location of feature popup in control panel from:
to:
Close #107
=> Fix control panel feature popup location

class/AMPageBase.cs
public class AMPageBase is not used for anything.
- Mark as deprecated in future release.
=> Deprecating AMPageBase

ActiveForums.dnn, ReleaseNotes.txt
=> v07.00.06 Release Prep

Classic.ascx.cs, class/Utilities.cs, controls/af_attach.ascx.cs, controls/af_confirmaction.ascx.cs
A few bug fixes for 07.00.06 RC1
- Unnecessary MapPath() for local resources
- remove unnecessary Page.ResolveUrl()
- restore missing code in Utilities.GetSharedResource()
=> Corrections for 07.00.06 RC1

Classic.ascx.cs, ControlPanel.ascx.cs, CustomControls/ServerControls/UserStats.cs, CustomControls/UserControls/TopicView.cs, CustomControls/UserControls/TopicsView.cs, CustomControls/UserControls/WhatsNewRSS.cs, ForumSettings.ascx.cs, class/SettingsBase.cs, components/Common/HandlerBase.cs, components/Users/UserController.cs, controls/af_attach.ascx.cs, feeds.aspx.cs
Remove usage of deprecated APIs:
DotNetNuke.Entities.Portals.PortalController.GetCurrentPortalSettings()
DotNetNuke.Entities.Users.UserController.GetCurrentUserInfo()
DotNetNuke.Framework.jQuery.RequestDnnPluginsRegistration()
DotNetNuke.Framework.jQuery.RegisterJQuery()
DotNetNuke.Framework.jQuery.RegisterJQueryUI()
DotNetNuke.Framework.jQuery.RequestRegistration()
DotNetNuke.Framework.jQuery.RequestUIRegistration()
Close #271
=> Remove usage of deprecated DNN platform APIs

class/Globals.cs
Added back commented-out code for a future release
=> Added back commented-out code for a future release

class/emoticons.cs
=> Escaping a single quote

Classic.ascx.cs, ControlPanel.ascx.cs, CustomControls/UserControls/ForumView.cs, ForumSettings.ascx.cs, class/emoticons.cs, controls/af_usersonline.ascx
07.07.07 RC3 issues
- fix emoticons html tag string
- forum settings page exception when full text options not installed
- lingering path / img tag issues
=> 07.07.07 RC3 issues

CustomControls/UserControls/TopicView.cs, scripts/afcommon.js
FIX: Liking a reply updates the displayed like count for the main topic not the reply; refreshing the page shows the correct like counts
FIX: For unauthenticated users, cursor should not change to pointer/hand when hovering over the like icon
Closes #320
=> FIX: Fixes to 'Like' UI

class/TemplateUtils.cs
Incorrect URLs in email notifications
- incorrect
- correct
Close #322
=> FIX: Incorrect URL in email notifications 

ActiveForums.dnn, ReleaseNotes.txt
Preparing for the 7.00.11 release
=> Tasks/release 7.0.11 prep

ActiveForums.csproj
several items removed from project needed to be removed from csproj
=> TASK: update csproj to remove deprecated items

ActiveForumViewer.ascx.cs, Classic.ascx.cs, CustomControls/ServerControls/ForumLoader.cs, CustomControls/UserControls/ForumView.cs, CustomControls/UserControls/SubmitForm.cs, CustomControls/UserControls/TopicView.cs, class/Utilities.cs, controls/af_usersonline.ascx.cs
Very quick fixes for a few issues with Forum Viewer
**NOTE: The viewer module was originally intended to provide a way to put (perhaps just selected) forums on a different page than the main forums module. Once you click on a link, you are taken to the main page where the Forums module is installed ** 
- Control Panel not working from Viewer
- User Online (if enabled for Forums) not working when Forums displayed on different page using the Viewer
Close #357
=> FIX: Some features not working correctly from Forums Viewer

controls/af_grid.ascx.cs
ENH: Use Friendly URLs on my/active/unread topics pages
Close #294
=> ENH: Use Friendly URLs on my/active/unread topics pages

Dnn.CommunityForums/Classic.ascx.cs, Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs, Dnn.CommunityForums/class/ForumBase.cs, Dnn.CommunityForums/class/ForumsConfig.cs, Dnn.CommunityForums/class/Globals.cs, Dnn.CommunityForums/class/Settings.cs, Dnn.CommunityForums/class/SettingsBase.cs, Dnn.CommunityForums/controls/af_post.ascx.cs, website/DesktopModules/ActiveForums/ActiveForums.dnn
Resolve compile and merge conflict issues
=> forumsconfig.cs and other compile issues

Dnn.CommunityForums/Classic.ascx.cs, Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs, Dnn.CommunityForums/class/Permissions.cs
merge issues with PR #270 introduced some compile errors
=> ENH: Improved Caching (PR 270 compile errors)

Dnn.CommunityForums/Module.build
Update WebSitePath in build script to reflect changes in folder structure.
=> Update WebsitePath in Module.build

README.md
=> Added New Logo to Readme

Dnn.CommunityForums/DnnCommunityForums.dnn
Change the old Icon for the new one
- changed icon for all 3 installed modules
Tested an upgrade of the module
Close #407
=> Change Module Icons fixes #407

Dnn.CommunityForums/Classic.ascx
Load the latest FontAwesome in the right order using DNN CRM
- Use DNN Client Resource Management to load 
- Load the latest FA 4
- Set load order to module so a skin can overrule
-
On a test site (it's a simple change ;-)
FYI this only a part of the solution for #410 
fixes #410
=> FontAwesome loading part of the solution for #410

Dnn.CommunityForums/images/Branding/Logo/README.md
Add logo documantation
- Added Readme.md file
Close #405
=> Logo documentation fixes #405

Dnn.CommunityForums/scripts/afcommon.js, Dnn.CommunityForums/scripts/afmod.js
Corrects issue with extra slash in url for web api calls from Javascript.
Close #
=> FIX: Web API urls have extra slash

Dnn.CommunityForums/handlers/forumhelper.ashx.cs
using statements removed from code file
=> FIX: usings missing in forumhelper.ashx.cs

Dnn.CommunityForums/ActiveForums.ascx
Added wrapper class to ActiveForums.ascx
- Added wrapper class to ActiveForums.ascx
Test site
Close #448
=> ENH: Add  a new Wrapper CSS class

Dnn.CommunityForums/App_LocalResources/SharedResources.resx
Add [RESX:Rating] resource string
Close #476
=> Add [RESX:Rating] resource string

Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/controls/af_searchquick.ascx.cs
"minisearch" needs to know tabid to pass to url generator
- pass tabid to minisearch control
Close #497
=> FIX: "minisearch" needs to know tabid to pass to url generator

Dnn.CommunityForums/controls/af_quickreply.ascx
Ctrl-Enter in quick reply submits the reply
entered a reply and pressed ctrl-enter
Close #502
=> ENH: ctrl+enter to submit on quick reply

Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Typo in activeforums_UI_MostReplies stored procedure
- fixed typo in SqlDataProvider
Tested before/after updating stored procedure
=> FIX: Typo in activeforums_UI_MostReplies stored procedure

Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/ControlPanel.ascx, Dnn.CommunityForums/ControlPanel.css
Added Module branding on top of the Control Panel
- Controlpanel.ascx added HTML
- RESX file added text
- Controlpanel.css added styling
Local test install 
Close #490
=> ENH: Module Branding #490

Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/class/Utilities.cs
I wrapped the text of all icon-text combinations in a `<span>` so we can hide the text on mobile
- Toolbar icons changed
- Topic toolbar icons changed
Build and install on local test site
Close #
=> #474 Swap icon texts in span

Dnn.CommunityForums/Classic.ascx.cs, Dnn.CommunityForums/CustomControls/ServerControls/ForumLoader.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/class/ForumBase.cs
Removes dead code and references to never-used ".htm" templates.
Close #525
=> TASK: Remove dead-code & template path variables

Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/class/Injector.cs, Dnn.CommunityForums/controls/af_modtopics.ascx.cs, Dnn.CommunityForums/controls/af_quickreply.ascx.cs, Dnn.CommunityForums/controls/af_usersonline.ascx, Dnn.CommunityForums/controls/af_usersonline.ascx.cs, Dnn.CommunityForums/controls/af_usersonline.ascx.designer.cs, Dnn.CommunityForums/module.css, Dnn.CommunityForums/scripts/afcommon.js, Dnn.CommunityForums/scripts/afutils.js
Modernized collapsible sections 
- Updates old "arrows_down.png" in main UI (not control panel) to use FontAwesome icons for:
- users online
- quick reply
- moderation panel
- updated javascript/jquery to be consistent and remove duplication
- update cookies (from javascript not server side) to save/retrieve settings for each control that is collapsible
Tested against dev install.
Close #471
=> ENH: new collapsible section logic and font awesome icons

Dnn.CommunityForums/08.00.00.txt, Dnn.CommunityForums/ReleaseNotes.txt
themes/module.css not used in v7; remove from existing installations during upgrade.
- add to 08.00.00.txt to remove file during upgrade
Local install upgrade from 07.00.12
Close #552
=> TASK: Remove not used themes/module.css 

Dnn.CommunityForums/controls/af_post.ascx, Dnn.CommunityForums/module.css
I only when for the invalid HTML and then I also did a buch more ;-)
- Make the HTML valid
- Change the icon to Font Awsome
- Add new dfc-css classes
- Add styling to module.css
Local test install
Close #577
=> Make the preview window work :-) #557

Dnn.CommunityForums/ControlPanel.css
Fix unreadable links in ControlPanel
- Changed the link color in ControlPanel.css
- Item 2
Local test site
Close #570
=> Changed controlpanel.css so links a readabel #570

Dnn.CommunityForums/BuildScripts/ModulePackage.targets, Dnn.CommunityForums/DnnCommunityForums.csproj
TASK: Include readme.md files in installations
- add readme.md to ModulePackage.targets 
Tested upgrade on local install
Close #549
=> TASK: Include readme.md files in installations

Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
Changed Previous and next images to use FontAwesome icons #522
Local test site
Close #522
=> ENH: Changed images to FontAwesome icons #522

Dnn.CommunityForums/class/Utilities.cs
Improve the Quick Search HTML for styling
- Change BR -> DIV
- All new classes are #459 
- Changed wrapping span to div
- Wrapped parts in appropriate div
- 
Local installation
Close #557
=> ENH: Improved Quick Search HTML #577

Dnn.CommunityForums/class/Utilities.cs
Changed the toolbar Icons
Build and install on local test site
- [x ] Feature solution
Close #550
=> ENH: Changed Toolbar Icons #550

Dnn.CommunityForums/themes/README.md
Moved Readme info to Wiki and linked to it
Close #595
=> Moved info to Wiki #595

Dnn.CommunityForums/themes/community-default/_less/parts/_quick-reply.less, Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx, Dnn.CommunityForums/themes/community-default/templates/QuickReply.ascx
Fix #587
- moved the wrapping div inside the [GROUPS] token
- Item 2
Local install
Close #587
=> BUG: 587 collapsed distances

Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs, Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs, Dnn.CommunityForums/class/Injector.cs, Dnn.CommunityForums/controls/af_modtopics.ascx.cs, Dnn.CommunityForums/controls/af_quickreply.ascx.cs, Dnn.CommunityForums/scripts/afutils.js
Modernizes collapsible sections in topic editor to use FontAwesome, Javascript/JQuery, and persist state in cookies
- Updates collapsible sections in topic editor:
- attachments
- topic review
- polls 
- categories
- additional options
Local install
Close #602
=> ENH: Modernize collapsible sections in topic editor

Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx
Fix missing icon
-Fix icon source to use correct (non-virtual) path.
Local install.
Close #623
=> FIX: Missing delete icon in control panel

Dnn.CommunityForums/module.css
.dcf-collapsible {
text-align: center;
padding: 0.2em ;
width: 1.8em;
cursor: pointer;
float: right;
font-size: 1.1em !important;
background: #eee;
border-radius: 50%;
position:relative;
z-index: 2;
}
Local install of community website
Close #625
=> ENH: Added styling for new Chevron Icons #625

Dnn.CommunityForums/module.css
Improved distance between icon and text:
- module.css
Local installs
Close #627
=> Fixes #627 Icon text distance

Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Fix flood interval control issue when using quick reply
Close #639
=> FIX: Flood interval error when using quick reply

Dnn.CommunityForums/config/templates/QuickReply.ascx
Unclosed tag in Quick Reply template
Close #641
=> FIX: Unclosed tag in quick reply template

Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn, Dnn.CommunityForums/Properties/AssemblyInfo.cs, Dnn.CommunityForums/ReleaseNotes.txt
=> Updated release notes & release numbers

Dnn.CommunityForums/module.css
Should not have color:white 
- CSS change in module.css for color:white in div.dcf-mod-edit-wrap
Local install
Close #654
=> FIX: Unreadable/invisible labels when moderating a post

Dnn.CommunityForums/Deprecated/API.cs, Dnn.CommunityForums/class/Data/AttachmentsDB.cs, Dnn.CommunityForums/class/ForumController.cs, Dnn.CommunityForums/class/Permissions.cs, Dnn.CommunityForums/components/Social/ActiveSocial.cs, Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
Refactoring to use constants rather than hard-coded values
=> TASK: Use constants rather than "-1" & "-3" for DNN "all users" and "unauthenticated" users

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/ControlPanel.css, Dnn.CommunityForums/controls/admin_templates.ascx, Dnn.CommunityForums/controls/admin_templates.ascx.cs, Dnn.CommunityForums/controls/admin_templates.ascx.designer.cs
Add theme name and template folder to Control Panel templates list
- UI updates
- Added resource strings to ControlPanel.resx:
- [RESX:Template] 
- [RESX:Theme] 
- Added resource strings to SharedResources.resx:
- [RESX:Folder] 
Local install
Close #569
=> ENH: Show theme and template folder in Control Panel templates list

Dnn.CommunityForums/ActiveForumViewer.ascx, Dnn.CommunityForums/ActiveForumViewer.ascx.cs, Dnn.CommunityForums/class/Utilities.cs
Incorrect layout of forums from companion Viewer module
- needed div to provide CSS scope to match main module
- toolbar links in Viewer module need to stay within the viewer module (the toolbar is "owned" by the main module, but the main module and the viewer module each need to be cached separately)
Local install.
Forums module:
Viewer module showing correct layout matching main module:
Close #692
=> FIX: CSS and URL issues with Forum Viewer module

Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
After upgrading from pre-v8 to v8 or higher, an extra record is in the ModuleDefinitions table (resulted from the DNN Community Forums rebranding done in v8 #394) 
- Remove extra record from ModuleDefinitions
1. Install v7.0.12
2. Only one record in ModuleDefinitions
3. Upgrade to 08.00.01
4. Now TWO records in ModuleDefinitions
5. Place module on page -- TWO copies get put on page
6. Delete modules and empty recycle bin; clean page
7. Install new 8.01.00 release with this PR
8. No longer extra record in ModuleDefinitions
9. Place module on page -- NO MORE DUPLICATE
Close #520
=> Duplicated module when placing on page

Dnn.CommunityForums/Classic.ascx.cs, Dnn.CommunityForums/active/amlib.js, Dnn.CommunityForums/controls/htmlcontrols/quickedit.ascx
Fixes two modal UI issues
- fix modal dialog centering
- enlarge topic options editor
local install.
First issue is positioning of modal dialogs.
Before:
After:
Second issue is that the topic option editor is undersized.
Before:
After:
Close #679
=> FIX: modal UI issues

Dnn.CommunityForums/Controllers/TopicController.cs, Dnn.CommunityForums/controls/af_grid.ascx.cs, Dnn.CommunityForums/controls/af_search.ascx.cs
Fix some search-related issues found in testing.
- Retrieval of icon for each topic (read/unread, etc. ) was moved to topic controller, but one parameter isn't available from search page
- Marked some methods in the search page for future deprecation, hoping to convert to a template, but haven't done so yet, and still need the methods
- Had switched out a "keyword" class for a List<string> which doesn't work with a data repeater
=> FIX: Fix some search-related issues

Dnn.CommunityForums/controls/af_post.ascx.cs
ReplyId missing in process queue when not using quick reply
=> FIX: Reply not posting (correct) ReplyId to Process Queue :(

Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs, Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx
ENH: support [GROUPNAME] [FORUMGROUPID] tokens in [GROUP] section in ForumView
Local install
=> ENH: support [GROUPNAME] [FORUMGROUPID] tokens in [GROUP] section in ForumView

Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/class/Globals.cs, Dnn.CommunityForums/config/templates/ToolBar.ascx, Dnn.CommunityForums/themes/community-bootstrap/templates/ToolBar.ascx, Dnn.CommunityForums/themes/community-default/templates/ToolBar.ascx
Change 'Filters' in toolbar to 'Filtered Topics'
Local install
=> ENH: Change 'Filters' in toolbar to 'Filtered Topics'

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/Messages.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/WhatsNew.ascx.fr-FR.resx, Dnn.CommunityForums/DnnCommunityForums.csproj
=> ENH: Add French translations

Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx, Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.es-ES.resx, Dnn.CommunityForums/App_LocalResources/Messages.ascx.es-ES.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx, Dnn.CommunityForums/App_LocalResources/WhatsNew.ascx.es-ES.resx
=> Reviewed spanish translation

Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/class/Utilities.cs, Dnn.CommunityForums/controls/af_usersonline.ascx, Dnn.CommunityForums/controls/profile_mypreferences.ascx, Dnn.CommunityForums/controls/profile_mysubscriptions.ascx
Review of Spanish translation found a few missing translations
Close #823
=> FIX: Missing translations

Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
Translations for French were incomplete (only contained first line of SharedResources) and have been re-generated:
Close #832
=> FIX: Add missing French translations

Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/class/Utilities.cs, Dnn.CommunityForums/controls/af_post.ascx.cs
HTML decoding needed for subject & summary in topics view
Local install
Before:
After:
Close #835
=> FIX: HTML decoding needed for subject & summary in topics view

Dnn.CommunityForums/module.css
UI tweaks for collapsible sections in topic editor 
- Added some basic CSS for collapsible section headers
Local install
Close #830
=> ENH: minor CSS tweaks in topic editor

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx, Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
Change DotNetNuke to DNN in resource files 
Close #822
=> ENH: Change DotNetNuke to DNN in resource files

Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx, Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
Topic / Forum subscriber counts not incrementing in bootstrap theme
- Add `<span>` tags for subscriber counts to community-bootstrap templates
Local install
Close #854
=> FIX: Topic / Forum subscriber counts not incrementing in bootstrap theme

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/Messages.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/WhatsNew.ascx.fr-FR.resx
=> Updated french localization

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/Messages.ascx.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
Corrected nl-NL language pack
Local install
Close #873
=> Checked and corrected the nl-NL translations

Dnn.CommunityForums/module.css
Make the filtered topic dropdown a bit wider so other languages fit too.
- Changed module.css
- Removed the blue-grey color as it's might conflict with some themes
- 
local install
Close #866
=> Fixed with of dropdown

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx, Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx, Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
IMO we don't need these anymore, but @johnhenley correct me if I'm wrong..
Removed the Enterprise texts from all Language Files
Not
Close #872
=> ENH: Removed the "Enterprise version text" from the language files

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx, Dnn.CommunityForums/ControlPanel.css, Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx, Dnn.CommunityForums/controls/admin_templates.ascx
#867:
#868:
#869:
Local install
Close #867 
Close #868
Close #869
=> Contro panel Fixes #867 #868 #869

Dnn.CommunityForums/Controllers/PermissionController.cs, Dnn.CommunityForums/components/Topics/TopicsController.cs
Permissions controller not evaluating "All Users" and "Unauthenticated Users" in some conditions. 
- Add "All Users" and "Unauthenticated Users" to Portal roles when evaluating permissions.
Local install
Close #894
=> FIX: Evaluate "All Users" and "Unauthenticated Users" in Permissions Controller

Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
nl-NL translation for StartedHeader translation
Local install
#901
=> Correction for #901 Started By in nl-NL

Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/Controllers/PermissionController.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/module.css, Dnn.CommunityForums/scripts/afcommon.js, Dnn.CommunityForums/scripts/afmod.js, Dnn.CommunityForums/scripts/resx.js
Locking and Pinning a topic were not working nor providing any feedback in Topic View. In addition, the UI was not dynamic. If you locked a topic, the UI didn't change to remove options for replying--that only happened when the page was reloaded.
- Updated UI elements and related javascript
- more dynamic (e.g. change UI text between 'lock' and 'unlock', 'pin' and 'unpin', and change icons as changes are made).
- hide/show reply link and quick reply based on locked status
- Moved lock and pin javascript functions from `afmod.js` to `afcommon.js` (users can be assigned Pin and Lock security separate from Moderate)
Local install
Close #883
=> ENH: Improve UI for Lock and Pin functions

Dnn.CommunityForums/ForumSettings.ascx.cs
Allow Friendly URL module setting for multi-language sites
Local install
Close #906
=> FIX: Allow Friendly URL module setting for multi-language sites

Dnn.CommunityForums/ReleaseNotes.txt
From 
Also, please know that this version of the forums is not meant to be used with Bootstrap 3 and/or the DNN Xcilliin theme.  
To
Also, please note that this version of the community-bootstrap theme will not work with Bootstrap 3 and/or the DNN Xcillion theme.
=> Corrected note on Bootstrap theme with Bootstrap3

Dnn.CommunityForums/ReleaseNotes.txt
Minor updates to the release notes. 
- Updated `"` to be `&quot;`.  
- Removed RC messages.  
EVS and installing locally.  
N/A
=> Tasks/release 8.1

Dnn.CommunityForums/Controllers/ModerationController.cs
Moderation notification not sent
- Restore missing code removed during merge conflict
Close #938
=> FIX: moderation notification not sent

Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/class/Globals.cs
Topic paging not working
- Need to include page size/current page in cache key
Local install
Close #933
=> FIX: Topic/Topics view caching needs to include page size / current page

Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/ReleaseNotes.txt
Preparing for the 8.1.1 release.  
- Updated release notes. 
- Formatted whitespace in the manifest 
EVS, local install 
N/A
=> Preparing for 8.1.1 release

Dnn.CommunityForums/controls/af_post.ascx.cs
Not redirected to new page after submitting edits to an existing reply
- Fix logic not doing redirect
Close #962
=> FIX: Not redirected to new page after submitting edits to an existing reply

Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn, Dnn.CommunityForums/ReleaseNotes.txt
=> Updates for 08.01.02 GA release

Dnn.CommunityForums/ReleaseNotes.txt
Update Release notes for 08.01.02
=> Update Release notes for 08.01.02 Release

Dnn.CommunityForums/controls/af_modtopics.ascx.cs
fixes #995
- The class used for the buttons was "dnnTertiaryaryAction", changed that to "dnnTertiaryAction"
Local install
Close #995
=> FIX: Moderate button styling issue #995

Dnn.CommunityForums/controls/af_modtopics.ascx.cs
Fix CSS class name for moderator buttons 
- Tertiary button class misspelled
Local install
Before:
After:
Close #995
=> FIX: Moderator buttons missing style

Dnn.CommunityForums/DnnCommunityForums.csproj
Remove obsolete attributes from csproj file.
Close #989
=> TASK: Update csproj for invalid SourceCodeControl attributes

Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn, Dnn.CommunityForums/Properties/AssemblyInfo.cs, Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Create 8.2 release
- Update version numbers in AssemblyInfo, manifests
- Create empty 08.02.00.SqlDataProvider
Close #986
=> TASK: Create 8.2 release

.gitignore, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/StyleCop.json, Dnn.CommunityForums/app.config, Dnn.CommunityForums/packages.config, Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj, Dnn.CommunityForumsTests/StyleCop.json, Dnn.CommunityForumsTests/packages.config
Install and configure StyleCop and Microsoft.CodeAnalysis.NetAnalyzers to use for code quality improvements. 
No changes to code made in this PR; this is just installation and configuration.
Close #779
=> TASK: Install and configure StyleCop and Microsoft.CodeAnalysis.NetAnalyzers

Dnn.CommunityForums/scripts/usereditor.js
usereditor.js updateUser() function expecting back json data but the web api call returns none; 
- remove dataType parameter from ajax call
Local install
Close #1002
=> FIX: Update User Error Message

Dnn.CommunityForums/Classic.ascx.cs
When you log out from my settings / my subscriptions pages, redirect to forums view
Local install
Close #981
=> FIX: Don't show my settings / my subscriptions after logged out

Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.nl-NL.resx
Found some weird wording and corrected them
- Dutch language pack
Local install
Close #
=> ENH: Some Dutch translation corrections

Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn, Dnn.CommunityForums/Properties/AssemblyInfo.cs
Create 8.2 release
(redo of PR #987; changes overwritten).
- Update version numbers in AssemblyInfo, manifests
- Create empty 08.02.00.SqlDataProvider
Close #986
=> TASK: Create 8.2 release (re-do PR #987)

Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/Controllers/TopicTrackingController.cs, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/Entities/TopicTrackingInfo.cs
DAL2 for activeforums_Topics_Tracking
- `TopicTrackingInfo` Entity 
- `TopicTrackingController` Controller
Close #1024
=> TASK: DAL2 for activeforums_Topics_Tracking

Dnn.CommunityForums/controls/af_quickjump.ascx.cs
Forum "quick jump" control throwing errors
Local install
Close #1034
=> FIX: "quick jump" control issues 

Dnn.CommunityForums/Controllers/ReplyController.cs, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/Entities/IPostInfo.cs, Dnn.CommunityForums/Entities/ReplyInfo.cs, Dnn.CommunityForums/Entities/TopicInfo.cs
Add IPostInfo object interface to use to handle common properties between TopicInfo and ReplyInfo.
Close #1039
=> TASK: Add IPostInfo object interface

Dnn.CommunityForums/Controllers/ReplyController.cs, Dnn.CommunityForums/Services/ForumServiceController.cs, Dnn.CommunityForums/Services/ModerationService.cs, Dnn.CommunityForums/controls/af_modreport.ascx.cs, Dnn.CommunityForums/controls/af_modtopics.ascx.cs, Dnn.CommunityForums/controls/af_post.ascx.cs
Update method calls for ReplyController from GetReply() to GetById() to standardize on DAL2 method name.
Close #1055
=> TASK: ReplyController update method calls from GetReply() to GetById()

Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Additional stored procedure changes to to support removing LastPostDate from `activeforums_ForumTopics`
- Corrected JOIN in stored procedure `activeforums_UI_TopicsDisplay` 
- Updated stored procedure `activeforums_UI_MyTopicsView` remove reference to LastPostDate from `activeforums_ForumTopics`
Local install
Close #1026
=> FIX: Couple of tweaks to SQL to support changes for LastPostDate

Dnn.CommunityForums/Controllers/TopicTrackingController.cs, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/Entities/ForumInfo.cs, Dnn.CommunityForums/Entities/ForumUserInfo.cs, Dnn.CommunityForums/Entities/ReplyInfo.cs, Dnn.CommunityForums/Entities/TopicInfo.cs, Dnn.CommunityForums/Enums/ForumStatus.cs, Dnn.CommunityForums/Enums/PostStatus.cs, Dnn.CommunityForums/Enums/ReplyStatus.cs, Dnn.CommunityForums/Enums/TopicStatus.cs
Adds enums for forum/topic/post statuses and centralized methods for returning statuses and CSS classes based on status.
Note: Tokens/replacement logic will be added in a separate PR; this is just supporting code.
- Updated wiki documentation:
https://github.com/DNNCommunity/Dnn.CommunityForums/wiki/Status-CSS-Class-Tokens
Close #468
=> TASK: Modernize Forum/Topic/Reply statuses

Dnn.CommunityForums/Controllers/ForumController.cs
Add GetLastPostSubjectLinkTag() method to ForumController
(code actually using this method will be in future PR for token replacement)
Close #1059
=> TASK: Add GetLastPostSubjectLinkTag method to ForumController

Dnn.CommunityForums/Controllers/EmailController.cs, Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs, Dnn.CommunityForums/class/Email.cs, Dnn.CommunityForums/class/ParamBuilder.cs, Dnn.CommunityForums/class/UserProfiles.cs, Dnn.CommunityForums/class/Utilities.cs
Various updates to methods and deprecations.
Close #1065
=> TASK: various updates

Dnn.CommunityForums/Controllers/ForumUserController.cs, Dnn.CommunityForums/Services/Controllers/ForumController.cs, Dnn.CommunityForums/Services/Controllers/UserController.cs, Dnn.CommunityForums/class/UserProfiles.cs, Dnn.CommunityForums/controls/af_grid.ascx.cs, Dnn.CommunityForums/controls/af_post.ascx.cs, Dnn.CommunityForums/controls/af_profile.ascx.cs, Dnn.CommunityForums/controls/af_search.ascx.cs, Dnn.CommunityForums/controls/af_usersonline.ascx.cs
Updates for GetDisplayName in ForumUserController
Close #1067
=> TASK: Additional method signature for GetDisplayName ForumUserController

Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Corrects typo in 08.02.00.SqlDataProvider
- Added a space to UPDATE{databaseOwner}
Local install
Close #1073
=> FIX: Corrected typo in 08.02.00.SqlDataProvider

Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/app.config, Dnn.CommunityForums/packages.config, Dnn.CommunityForumsTests/app.config
Add NewtonSoft JSON package via NuGet
Close #1084
=> TASK: Add NewtonSoft JSON package via NuGet

Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj, Dnn.CommunityForumsTests/packages.config
Update NUnit & Moq
Close #1086
=> TASK: Update NUnit & Moq

Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/class/Utilities.cs
Module setting for template caching not checked when loading toolbar template
Local install
Close #472
=> ENH: Use template caching module setting for Forums toolbar

Dnn.CommunityForums/controls/af_grid.ascx, Dnn.CommunityForums/controls/af_search.ascx
Add wrapper div's to search results and filtered topics
Close #480
=> ENH: add wrapper DIVs

Dnn.CommunityForums/Controllers/ReplyController.cs, Dnn.CommunityForums/Controllers/TopicController.cs, Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/class/Utilities.cs, Dnn.CommunityForums/components/Social/ActiveSocial.cs
Updates a journal item when a post (topic or reply) is updated.
- Item 1
- Item 2
Local install
original journal
updated post
updated journal
Close #821
=> ENH: Update DNN journal item when updating a post

Dnn.CommunityForums/sql/08.02.00.SqlDataProvider, Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Add indexes to activeforums_Topics and activeforums_Replies to retrieve by ContentId
Local install
Close #1100
=> TASK: Add indexes to retrieve Topics and Replies by ContentId

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx, Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx, Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx, Dnn.CommunityForums/Controllers/PermissionController.cs, Dnn.CommunityForums/Entities/PermissionInfo.cs, Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
Separates control security settings into basic, advanced, and moderator/administrator.
Local install
Close #931
=> ENH: More organized security in control panel

Dnn.CommunityForums/Services/Controllers/ControllerBase.cs, Dnn.CommunityForums/Services/Controllers/ForumController.cs, Dnn.CommunityForums/Services/Controllers/LikeController.cs, Dnn.CommunityForums/Services/Controllers/ReplyController.cs, Dnn.CommunityForums/Services/Controllers/TagController.cs, Dnn.CommunityForums/Services/Controllers/TopicController.cs, Dnn.CommunityForums/Services/Controllers/UserController.cs, Dnn.CommunityForums/Services/ForumAuthorizeAttribute.cs, Dnn.CommunityForums/Services/ServicesHelper.cs
Adds exception logging to Web API controller methods
Close #1051
=> TASK: Add exception handling to Web API methods

Dnn.CommunityForums/class/TemplateUtils.cs, Dnn.CommunityForums/themes/community-bootstrap/templates/ProfileInfo.ascx, Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx, Dnn.CommunityForums/themes/community-default/templates/ProfileInfo.ascx, Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
Update tokens in delivered ProfileInfo templates
Local install
Close #1119
=> ENH: Token updates for ProfileInfo templates

Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs, Dnn.CommunityForums/class/ForumBase.cs, Dnn.CommunityForums/class/TemplateCache.cs, Dnn.CommunityForums/class/TemplateUtils.cs, Dnn.CommunityForums/class/Utilities.cs
When loading template, if template contains [DCF:TEMPLATE-xxxx] token(s), load xxx template directly.
Local install
Close #1124
=> ENH: Load nested templates using [DCF:TEMPLATE-xxxx] token

Dnn.CommunityForums/Controllers/TokenController.cs, Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
Fix Topic View issues found during pre-release testing
- FIX: LIkes in topic view should use contentId not TopicId/ReplyId
- FIX: Don't show topic part of template in topic view if only showing replies
- TASK: Don't use tokens.config for tags input box
Local install
Close #1139 
Close #1140
=> FIX: Topic View issues found during pre-release testing

Dnn.CommunityForums/App_LocalResources/LegacyTokenResources.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/Entities/ReplyInfo.cs, Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs, Dnn.CommunityForums/config/templates/PostActions.ascx, Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Updates for "mark answer"/"accepted answer"
- Use font awesome checkmark icons
- Mobile responsive markup
- Update token replacement and `post actions` template
- Minor tweak to stored procedure to unmark any previously marked answers if you change topic to unresolved and select a different answer
Local install
Mobile (mark as answer)
Mobile (accepted answer)
Close #1042
=> ENH: Font awesome icon for "correct answer"

Dnn.CommunityForums/controls/af_modtopics.ascx.cs
Minor tweaks for moderation page.
(also added separate issue #1146 to update page to use a template and topic replacement)
1. Adds link to user's profile (opens in separate tab)
2. Adds 'topic review' for a reply to let moderator see previous content for this topic 
Local install
Close #1041
=> ENH: Minor tweaks to moderation page

Dnn.CommunityForums/themes/community-bootstrap/templates/ForumView.ascx, Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
Fix forum group collapse
- Correct [GROUP] token location in community templates
Local install
Close #1153
=> FIX: correct [GROUP] token location in ForumView template

Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
Filter forum view if group specified on query string
Local install
Close #1152
=> FIX: Filter forum view if group specified on query string

Dnn.CommunityForums/Controllers/ForumController.cs, Dnn.CommunityForums/Controllers/ForumGroupController.cs, Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs, Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Corrects issue with deleting forums and forum groups
- Corrects issue with deleting forums and forum groups
- Deletes forum subscriptions when deleting forum
Local install
Close #1156
=> FIX: Delete forum not working; delete should remove subscriptions

Dnn.CommunityForums/ActiveForumViewerSettings.ascx.cs, Dnn.CommunityForums/Controllers/ForumController.cs, Dnn.CommunityForums/Controllers/ForumTopicController.cs, Dnn.CommunityForums/Controllers/ForumUserController.cs, Dnn.CommunityForums/Controllers/SubscriptionController.cs, Dnn.CommunityForums/CustomControls/HTML/ControlPanel.cs, Dnn.CommunityForums/Deprecated/Cache.cs, Dnn.CommunityForums/ForumSettings.ascx.cs, Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs, Dnn.CommunityForums/class/DataProvider.cs, Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs, Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
Move some forum table CRUD methods from stored procedures to use DAL2 controller/object
- Update code using sproc methods to use DAL2 controller/object
- Mark for deprecation
- `Forums_Delete`
- `Forums_List`
- `Forum_ConfigCleanUp`
NOTE: Leaving `Forum_Save` for future.
local install
Close #1160
=> TASK: Replace forum list & delete sprocs with DAL2

Dnn.CommunityForums/Controllers/ForumGroupController.cs, Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
Continuation of PR #1166
Update references in control panel to use new common FeatureSettings class.
Close #1163
=> TASK: Update control panel for FeatureSettings class

Dnn.CommunityForums/ActiveForumViewerSettings.ascx.cs, Dnn.CommunityForums/ControlPanel.ascx.cs, Dnn.CommunityForums/Controllers/ForumGroupController.cs, Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs, Dnn.CommunityForums/CustomControls/ServerControls/TopicSort.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs, Dnn.CommunityForums/WhatsNewOptions.ascx.cs, Dnn.CommunityForums/controls/_default.ascx.cs, Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs, Dnn.CommunityForums/controls/af_grid.ascx.cs, Dnn.CommunityForums/controls/af_markallread.ascx.cs, Dnn.CommunityForums/controls/af_members.ascx.cs, Dnn.CommunityForums/controls/af_modban.ascx.cs, Dnn.CommunityForums/controls/af_modreport.ascx.cs, Dnn.CommunityForums/controls/af_modtopics.ascx.cs, Dnn.CommunityForums/controls/af_pollvote.ascx.cs, Dnn.CommunityForums/controls/af_post.ascx.cs, Dnn.CommunityForums/controls/af_quickjump.ascx.cs, Dnn.CommunityForums/controls/af_quickreply.ascx.cs, Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs, Dnn.CommunityForums/controls/af_searchquick.ascx.cs, Dnn.CommunityForums/controls/af_sendto.ascx.cs, Dnn.CommunityForums/controls/af_topicsort.ascx.cs, Dnn.CommunityForums/controls/af_topicstatus.ascx.cs, Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
Update Redirect() method calls for consistent and correct usage per 
https://learn.microsoft.com/en-us/dotnet/api/system.web.httpresponse.redirect?view=netframework-4.8.1
- Response.Redirect(url, false) followed by CompleteRequest()
Local install
Close #970
=> TASK: Update Redirect() method calls for consistent and correct usage

Dnn.CommunityForums/CustomControls/ServerControls/Callback.cs, Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/ForumSettings.ascx.cs, Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs, Dnn.CommunityForums/feeds.aspx.cs
Update regex usage to use DNN RegExUtils.GetCachedRegex 
Local install
Close #1158
=> TASK: Use DotNetNuke.Common.Utilities.RegexUtils.GetCachedRegex

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx, Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx, Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx, Dnn.CommunityForums/ControlPanel.css, Dnn.CommunityForums/Entities/FeatureSettings.cs, Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
Addendum for PR #1171 to put inheritance labels on subforums in control panel.
Close #1171
=> ENH: show inheritance labels in control panel for subforums

Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx, Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx, Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx, Dnn.CommunityForums/ControlPanel.css, Dnn.CommunityForums/controls/admin_manageforums.ascx, Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
Update UX to use icons and tooltips rather than text for forum inheritance in control panel
Local install
Close #1161
=> ENH: update UX for inheritance labels in control panel

Dnn.CommunityForums/module.css
- Add margin to the moderate buttons
Local install
Close #969
=> Fix: Moderate button styling #969

Dnn.CommunityForums/Controllers/ForumController.cs
"What's New" module can aggregate multiple instances of the Forums module; don't use module-scoped DAL2 GetById() when retrieving forums for "What's New" module.
Local install
Close #1190
=> FIX: What's new not loading forums

Dnn.CommunityForums/Entities/TopicInfo.cs, Dnn.CommunityForums/class/Utilities.cs
With new token replacement logic, topic icons were not displaying.
Local install
Close #
=> FIX: missing topic icons

Dnn.CommunityForums/components/Controls/ControlUtils.cs
FIX: likes views not working with old/non-friendly URLs
Local install
Close #801
=> FIX: likes views not working with old/non-friendly URLs

Dnn.CommunityForums/Controllers/ForumController.cs, Dnn.CommunityForums/Controllers/ForumGroupController.cs, Dnn.CommunityForums/Controllers/ReplyController.cs, Dnn.CommunityForums/Controllers/RepositoryControllerBase.cs, Dnn.CommunityForums/Controllers/TopicController.cs
Correct caching issue
Local install
Close #1210
=> FIX: correct caching issue when loading topics/replies

Dnn.CommunityForums/Controllers/ReplyController.cs, Dnn.CommunityForums/Controllers/TopicController.cs, Dnn.CommunityForums/Entities/TopicInfo.cs, Dnn.CommunityForums/class/ForumsConfig.cs, Dnn.CommunityForums/controls/af_post.ascx.cs
Fix some issues encountered during upgrade testing
Local install
Close #1216
=> FIX: issues found during upgrade testing

Dnn.CommunityForums/Classic.ascx.cs, Dnn.CommunityForums/ControlPanel.css, Dnn.CommunityForums/Controllers/PermissionController.cs, Dnn.CommunityForums/Entities/FeatureSettings.cs, Dnn.CommunityForums/Entities/ForumInfo.cs, Dnn.CommunityForums/Entities/ForumUserInfo.cs, Dnn.CommunityForums/Entities/PermissionInfo.cs, Dnn.CommunityForums/Entities/ReplyInfo.cs, Dnn.CommunityForums/class/ForumsConfig.cs, Dnn.CommunityForums/components/Topics/TopicsController.cs, Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs, Dnn.CommunityForumsTests/Controllers/PermissionControllerTests.cs
Addresses some control panel issues encountered during pre-release testing with DNN Community site
- Restore parts of missing commit 392361cf in PR# 1173 (changed control panel inheritance labels to use icons)
- During upgrade and when saving permissions, sort permission set members (role IDs) to allow faster comparison
Local install copy of DNN community
Close #1161
=> FIX: few minor issues encountered in pre-release testing

Dnn.CommunityForums/Classic.ascx.cs, Dnn.CommunityForums/Controllers/ForumController.cs
Fix exceptions when using Forums with Social Groups integration
- Social integration with Forums was looking in tab settings for a module setting, and needs a fallback to also look at module settings.
Local install
Close #1229
=> FIX: Social integration exceptions

Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn, Dnn.CommunityForums/Properties/AssemblyInfo.cs, Dnn.CommunityForums/ReleaseNotes.txt
Preparing to release 8.2.1  
- Updated release number in DNN manifest files and project properties  
- Reduced release notes to better match what's in GitHub and make it easier/less confusing to read  
- Removed RC verbiage 
Tested the installation & upgrade.  
Close #
=> Tasks/release updates 8.2.1

Dnn.CommunityForums/Controllers/TopicController.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/Entities/AuthorInfo.cs, Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx, Dnn.CommunityForums/sql/08.02.02.SqlDataProvider
Various fixes for 08.02.01 release
- FIX: Edit Topic puts topic back into moderation
- FIX: Error deleting topic
- FIX: Topics view not loading
- FIX: Topic delete needs to call this.GetById() not base.GetById() in order to update cache
- FIX: JavaScript in control panel forum configuration
- FIX: Handle (hard-)deleted users when retrieving old posts
- FIX: Update UI stored procedures for TopicView/TopicsView to return more columns to fill object model without additional database trips
Local install
Close #1240 
Close #1241
Close #1242
Close #1243
=> FIX: Various UI issues with 8.2 release

Dnn.CommunityForums/Controllers/ForumUserController.cs, Dnn.CommunityForums/Entities/ForumUserInfo.cs, Dnn.CommunityForums/controls/af_sendto.ascx.cs, Dnn.CommunityForums/feeds.aspx.cs
Remove HttpContext reliance
Local install
Close #1258
=> FIX: Email notifications / remove HttpContext reference

Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn, Dnn.CommunityForums/Properties/AssemblyInfo.cs, Dnn.CommunityForums/ReleaseNotes.txt
Prepped for the latest GA release.  
- Release notes updated  
- Version number updates  
Built locally 
Close #1266
=> Tasks/release prep 9.2.3

Dnn.CommunityForums/sql/08.02.03.SqlDataProvider
Fixes botched SQL updates for 8.2.3
Local install
Close #1270
=> FIX: Botched SQL merge

Dnn.CommunityForums/Controllers/ForumController.cs, Dnn.CommunityForums/Controllers/ReplyController.cs, Dnn.CommunityForums/Controllers/TopicController.cs, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/Entities/TopicInfo.cs, Dnn.CommunityForums/sql/08.02.04.SqlDataProvider
Fixes/tweaks related to deleting a topic. 
- When marking a topic (or forum) read, check that topic (or forum) actually exists since it might have been (hard-)deleted
- When deleting topic or reply, clear caches used for topic view, topics view, and forum view
Close #1277
=> FIX: Issues when deleting a topic

Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
Topic view populate content DateUpdated from stored procedure.
Local install
Close #1282
=> FIX: Topic View populate DateUpdated 

Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs, Dnn.CommunityForums/class/TemplateUtils.cs, Dnn.CommunityForums/controls/af_attach.ascx.cs
Testing with DNN 10 RC1 revealed usage of a few APIs that are removed in DNN 10.
Local install
Close #1294
=> TASK: Remove deprecated API usage removed in DNN 10

Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn, Dnn.CommunityForums/Properties/AssemblyInfo.cs, Dnn.CommunityForums/ReleaseNotes.txt
Preparing for the 8.2.4 release. 
- Updated release notes  
- Updated version numbers  
- Tested builds  
Built locally 
Close #1296
=> Tasks/release 8.2.4

Dnn.CommunityForums/ReleaseNotes.txt
=> Added missing update to the release notes

Dnn.CommunityForums/config/templates/ToolbarSearchPopup.ascx
Enables enter key in popup search box 
Local install
Close #1311
=> ENH: Use Enter key in search popup

Dnn.CommunityForums/class/ForumsConfig.cs, Dnn.CommunityForums/class/Globals.cs
Don't overwrite existing templates when initializing/placing the module.
Local install
Close #1312
=> FIX: Don't overwrite existing templates

Dnn.CommunityForums/Controllers/ForumUserController.cs
Fixes two issues with 'ban user' feature
- exception when retrieving posts to remove from journal
- unable to 'ban' an already-deleted user (still need to remove content)
Local install
Close #1334
=> FIX: Issues with "ban user" feature

Dnn.CommunityForums/CustomControls/ServerControls/ActiveGrid.cs, Dnn.CommunityForums/CustomControls/ServerControls/Callback.cs, Dnn.CommunityForums/CustomControls/ServerControls/DatePicker.cs, Dnn.CommunityForums/CustomControls/ServerControls/MenuButton.cs, Dnn.CommunityForums/CustomControls/ServerControls/RequiredFieldValidator.cs, Dnn.CommunityForums/CustomControls/ServerControls/ScriptLoader.cs, Dnn.CommunityForums/DnnCommunityForums.csproj, Dnn.CommunityForums/WhatsNewOptions.ascx.cs, Dnn.CommunityForums/controls/af_post.ascx.cs, Dnn.CommunityForums/controls/af_topicscripts.ascx.cs
Remove some custom control scripts/images from being embedded resources
Standardize loading of scripts to use DNN ClientResourceManager
Local install
Close #1341
=> TASK: Remove embedded resources for scripts and custom controls images

Dnn.CommunityForums/config/templates/TopicResults.ascx
When combined with PR #1338, fixes some display issues in filtered topics views.
Local install
Close #1335
=> FIX: tweaks to filtered topic results template

Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/controls/af_searchadvanced.ascx, Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs, Dnn.CommunityForums/controls/af_searchadvanced.ascx.designer.cs
Updates advanced search page to use localization
Local install
Close #1347
=> ENH: Updates advanced search page to use localization

Dnn.CommunityForums/DnnCommunityForums.dnn
Update DNN "CoreVersion" in manifest to match supported DNN Platform 09.11.00
Close #1389
=> TASK: Update DNN "CoreVersion" in manifest

Dnn.CommunityForums/sql/09.00.00.SqlDataProvider
Converts NTEXT columns to NVARCHAR(MAX) for `activeforums_Content` and `activeforums_EmailNotificationQueue`.
(Note: although we are removing `activeforums_Templates`, it is also included for completeness).
- 09.00.00.SqlDataProvider scripts
- update manifest for 09.00.00.SqlDataProvider
Local install
Close #1184
=> TASK: Convert database columns from NTEXT to NVARCHAR(MAX)

Dnn.CommunityForums/DnnCommunityForums.csproj
Remove legacy `Analyzer` tags from csproj that prevent build.
Local build
Close #1425
=> TASK: Remove legacy Analyzer tags from csproj file

Dnn.CommunityForums/ReleaseNotes.txt
Updates release notes for 09.00.00
Close #1423
=> TASK: 09.00.00 release notes

Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/Entities/ForumGroupInfo.cs, Dnn.CommunityForums/Entities/ForumInfo.cs, Dnn.CommunityForums/Entities/ForumUserInfo.cs, Dnn.CommunityForums/Entities/LikeInfo.cs, Dnn.CommunityForums/Entities/ReplyInfo.cs, Dnn.CommunityForums/Entities/TopicInfo.cs, Dnn.CommunityForums/Services/Tokens/ForumsModuleTokenReplacer.cs, Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs, Dnn.CommunityForums/class/Utilities.cs, Dnn.CommunityForumsTests/Controllers/PermissionControllerTests.cs, Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Improves token replacement:
1. avoiding exceptions when topic contains curly braces, 
2. not causing entire page load to fail, and 
3. adding messages to admin log with details of exceptions encountered during token replacement.
- Updated `EncodeBrackets` and `DecodeBrackets` to handle curly braces causing exception in token replacement
- Refactored `GetProperty` token replacement methods to include error handling with try-catch blocks
- Exceptions during token replacement will no longer crash the entire page, just not replace a particular token
- Logs an exception to the admin log with details of the token replacement causing the exception
- Added resource entries for `TokenReplacementException` in multiple languages
- Added unit tests for encoding and decoding methods in …
=> FIX: Improved token replacement

Dnn.CommunityForums/ReleaseNotes.txt
Updates release notes for changes since RC2
Close #1460
=> TASK: Updated release notes 

Dnn.CommunityForums/scripts/afcommon.js
Collapsible sections not opening on first click
Local install
Close #1462
=> FIX: Collapsible sections not opening on first click

Dnn.CommunityForums/ReleaseNotes.txt
Update release notes for PR #1465
=> TASK: Update release notes

Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/Controllers/EmailController.cs, Dnn.CommunityForums/Controllers/ForumUserController.cs, Dnn.CommunityForums/CustomControls/HTML/TopicBrowser.cs, Dnn.CommunityForums/Entities/ForumUserInfo.cs, Dnn.CommunityForums/ReleaseNotes.txt, Dnn.CommunityForums/class/Utilities.cs, Dnn.CommunityForums/config/templates/SubscribedEmail.ascx, Dnn.CommunityForums/scripts/afcommon.js, Dnn.CommunityForums/sql/09.00.00.SqlDataProvider
Enhancement of email notification presentation to mimic DNN notifications and support localization.
- **SubscribedEmail.ascx**: Replaced the old email notification template with a new HTML structure for improved presentation
- **SharedResources.*.resx**: Moved text from notification template to resources to facilitate localization
- **EmailController.cs**: Updated `SendNotification` method to use `System.Text.Encoding.UTF8`
- **ForumUserController.cs**: Modified `GetAvatar` method to accept `PortalSettings` and updated its usage
Local install
Before:
After:
Close #1457
=> ENH: Modernize email notification template

Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/sql/09.00.00.SqlDataProvider, Dnn.CommunityForums/sql/09.00.01.SqlDataProvider
Correct SQL typo for incorrect position of {objectqualifier}
Close #1498
=> FIX: stubborn sql typo

Dnn.CommunityForums/controls/af_modtopics.ascx.cs, Dnn.CommunityForums/sql/09.00.01.SqlDataProvider
Correct page refresh when removing last post being moderated
Local install
Close #1500
=> FIX: Approving last post on moderation page not refreshing page

Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/Entities/ForumGroupInfo.cs, Dnn.CommunityForums/Entities/ForumInfo.cs
Change permissions checking during forum token replacement
Close #1501
=> FIX: Content not showing for some users

Dnn.CommunityForums/DnnCommunityForums.dnn, Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn, Dnn.CommunityForums/ReleaseNotes.txt
Release prep
- Updated release notes
- Updated version in manifests
Close #1505
=> TASK: 09.00.01 Release Prep

Dnn.CommunityForums/Services/Controllers/LikeController.cs, Dnn.CommunityForums/Services/Controllers/TopicController.cs, Dnn.CommunityForums/Services/ForumAuthorizeAttribute.cs, Dnn.CommunityForums/Services/ServicesHelper.cs
…n functions (e.g. Ban) should not require forumId to be passed to the API #1507
Updates Web API security checking "ForumsAuthorizeAttribute" for certain functions (e.g. Ban) to not require forumId to be passed to the API 
- Item 1
- Item 2
Local install
Close #1507
=> TASK: Web API security for non-forum-specific methods

Dnn.CommunityForums/sql/09.01.00.SqlDataProvider
Some additional SQL changes for removing "Last*" columns from `forums` table
Close #792
=> TASK: Additional work on `Last`* Columns removal from `forums` table

Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs, Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs, Dnn.CommunityForums/ReleaseNotes.txt, Dnn.CommunityForums/components/Helpers/URL.cs
Updates URL handling in navigation pager when not using friendly URLs
Local install
Close #1537
=> FIX: Incorrect links in pager when friendly URLs not enabled

Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.resx, Dnn.CommunityForums/Controllers/SubscriptionController.cs, Dnn.CommunityForums/CustomControls/HTML/ToggleSubscribe.cs, Dnn.CommunityForums/class/Subscriptions.cs, Dnn.CommunityForums/scripts/afcommon.js, Dnn.CommunityForums/scripts/resx.js, Dnn.CommunityForums/themes/community-bootstrap/templates/QuickReply.ascx, Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx, Dnn.CommunityForums/themes/community-default/templates/QuickReply.ascx, Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
Changes forum/topic subscription checkbox to a button
Local install
Close #1556
=> ENH: Change subscribe checkbox to button

Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx, Dnn.CommunityForums/App_LocalResources/SharedResources.resx
Change phrasing of 'Subscribe to Topics' user setting to 'Auto-Subscribe to My Topics'
Close #1579
=> ENH: Change phrasing of "Subscribe to Topics"
