DNNCommunity/Dnn.CommunityForums

- ActiveForums.dnn
#23 is caused by two issues IMO
1. Missing  /bin and /sql base paths in the manifest. > this is fixed in this PR
2. The resources file for the "Whatsnew" module is missing > @hismightiness how would you prefer to fix that?
Added \bin and \sql base paths
side note: I also Changed the owner of the WhatsNew Module to DNN community
#23 partly
Close #
> Fixes Part of #23 path issues for bin and sql + changed owner for "whatsnew"

- components/Common/ForumSettingsBase.cs
This is a workaround for [this issue in DNN](https://github.com/dnnsoftware/Dnn.Platform/issues/3495) that prevents users from saving settings when the new value only changed the casing. It closes #31 
- Created helper functions for updating tabmodulesettings and modulesettings
- removed unnecessary updating of internal settings dictionary (since DNN empties the cache after updating a setting)
- [x ] Fixes Bug
Close #31
> Workaround for DNN issue on updating settings

- CustomControls/UserControls/SubmitForm.cs
- class/Utilities.cs
- controls/af_post.ascx
- themes/_default/module.css
- Removed position Absolute
- Made the height of the div a bit higher so the border at the bottom shows correctly
- Made sure the "close" icon shows the correct cursor (pointer).
Please note that some of these change are done in module.css in the theme folder meaning that you need to fix your custom theme too.
Close #64
> Fix weird looking Preview pop-up #64

- CustomControls/UserControls/SubmitForm.cs
- class/Utilities.cs
This is the fix for HTML being decoded after posting.
It would be good to check the new code (for security) as I removed a few encodes and decodes
- The removed Decodes in class/Utilities.cs were not needed and they were preventing posting code example in the editor from being saved correctly
- CustomControls/UserControls/SubmitForm.cs > editor.HtmlEncode = false; 
Could now be set to false, because the unneeded Decodes above weer removed
fixes #73
> Fix HTML Encode & Decode issues #73

- scripts/afadmin.js
When there are SVG elements on a page an error is thrown because `elements[i].className` returns a [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString). According to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/className#notes), it is better to use `getAttribute('class')` when handling SVG elements.
- Use `getAttribute('class')` instead of `className`
> Use getAttribute('class') instead of className to support webpages with SVG elements

- class/UserProfile.cs
- components/Replies/Replies.cs
- components/Topics/Topics.cs
Fixed Flood support
Flood support is based on comparing the LastPostDate with the current date.
Although LastPostDate  is saved correctly after a post the cache for the UserProfile is not cleared.
So Flood support does not work unless you clear the DNN cache.
- Added a Profiles_ClearCache function. 
- Called that from the appropriate locations.
Close #79
> Fixed Flood support #fixes #79

- ForumSettings.ascx.cs
- components/Common/ForumSettingsBase.cs
Closes #111
This PR fixes the working of the Full Text switch in the settings of the module.
Cause of the issue was that the new value was read from the control, but actually enabling/disabling full text search in the DB was done based on the old value of the setting.
Close #111
> Fix full text search switch in settings

- class/ForumGroups.cs
- class/ForumInfo.cs
- class/ForumsConfig.cs
- config/defaultsetup.config
- controls/admin_manageforums_forumeditor.ascx
- controls/admin_manageforums_forumeditor.ascx.cs
- Enable HTML editor as the default editor when enabling HTMLd
- make HTML default for a new installation
Close #108
> Enable HTML editor by default when enabling HTML; make HTML installation default

- handlers/forumhelper.ashx.cs
- Call correct cache clearing API when moving topic (previous call was to clear cache for forum settings/templates not content)
Close #65
> Call correct cache clearing API when moving topic

- module.css
Made sure the parent of the collapse image with position absolute gets position:relative, to avoid the image from growing too large
Fixes #134 
Close #134
> Fix for iPad issue, img overlapping forum index links #134

- App_LocalResources/ControlPanel.ascx.resx
- App_LocalResources/ForumSettings.ascx.resx
- ForumSettings.ascx
- class/ForumsConfig.cs
- config/defaultsetup.config
Change Forums default settings to enable DNN Search when installing new instance.
- update delivered "delete behavior" from Remove Content Immediately to "Mark as Deleted"
- update delivered "index content" forum option 
Close #201
Close #202
> Update default settings to enable DNN search

- ActiveForumViewer.ascx.cs
- ActiveForumViewerSettings.ascx.cs
- ActiveForums.dnn
- BuildScripts/ModulePackage.targets
Older versions of Active Forums had the ability to show a forum group or forum on a different page than the one on which the Forums module was installed. This pull request reintroduces and packages that feature.
- Review previous code already in repo
- Correct options/settings module loading logic
- Build script/packaging to add module definition
Close #206
> Reintroduce standalone Forums Viewer module

- CustomControls/UserControls/TopicsView.cs
When using Forums module setting "Member name display format" = "Display name", and topic or reply is from an "anonymous" poster, topics view is displaying 'Anonymous' rather than the displayname entered by the anonymous poster.
-  An HTML tag was wrapped around the "Anonymous" string, causing the IF statement to ignore "Anonymous" users
- ,Source of variable substitution was from the Users table, rather than from the "Anonymous" user's entered name, which is stamped into the activeforums_Content table.
Close #204
> Fix displayed name for "anonymous" users 

- ActiveForums.csproj
- Classic.ascx.cs
- ControlPanel.ascx.cs
- CustomControls/UserControls/WhatsNewRSS.cs
- ReleaseNotes.txt
- Services/AdminServiceController.cs
- WhatsNew.ascx.cs
- WhatsNewOptions.ascx.cs
- class/ActiveAdminBase.cs
- class/SettingsBase.cs
- components/Extensions/ReWriter.cs
- components/Topics/TopicsController.cs
DNN Platform DotNetNuke.Entities.Modules.ModuleController .GetModuleSettings() and .GetTabModuleSettings() methods are being deprecated. In addition, they don't cache the settings, resulting in repeated database roundtrips to retrieve settings:
- Changed module settings retrieval logic in all affected classes
Database calls greatly reduced:
Close #252
> Replace deprecated DNN platform method GetModuleSettings() with .ModuleSettings property references

- components/Tokens/TokensController.cs
The file tokens.config is read constantly. Cache the file.
Related to epic issue #258
> Cache retrieval of tokens.config

- class/ForumBase.cs
A string concat update was done manually, which introduced a duplicate variable and a missing one at the same time.
> Removed duplicate, added missing var

- sql/07.00.05.SqlDataProvider
- sql/07.00.06.SqlDataProvider
- sql/07.00.07.SqlDataProvider
BUG: SqlDataProviders for 07.00.05/07.00.06/07.00.07 (re-)saved as UTF-8 BOM (rather than UTF-8) causing SQL errors during 07.00.10 upgrade.
> 07.00.10 Upgrade fails when executing SQL for 07.00.05

- ForumSettings.ascx
- Made inputs wider so the content does not get "cropped"
Fixes #317 
Close #317
> Modulesettings input widths fixes #317

- components/Replies/Replies.cs
- controls/af_quickreply.ascx.cs
FIX: Bad redirect when replying and using friendly URL rewriter
- In reply and quick reply, check if friendly URLs are used, and redirect to reply using #xxxx rather than &afc=xxxx
Close #324
> FIX: Bad redirect when replying and using friendly URL rewriter

- controls/af_post.ascx.cs
FIX: Bad redirect when replying and using friendly URL rewriter
(CONTINUATION of #325)
- In reply posting, check if friendly URLs are used, and redirect to reply using #xxxx rather than &afc=xxxx
Close #324
> BUG: Bad redirect when replying and using friendly URL rewriter

- sql/07.00.10.SqlDataProvider
BUG: 07.00.10.SqlDataProvider formatted as UTF-8 BOM (rather than UTF-8) causing SQL errors during 07.00.11 upgrade.
> 07.00.11 Upgrade fails when executing SQL for 07.00.10

- Dnn.CommunityForums/config/defaultsetup.config
Merge of defaultsetup.config resulted in duplicated templates tag
- remove duplicated tag
- 
Close #384
> Remove duplicate templates tag in defaultsetup.config

- Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Uninstall fails when dropping table activeforums_Tags
- add missing DROP CONSTRAINT to uninstaller for activeforums_Tags
Installed previous version and uninstalled it to verify table was not removed.
From event log:
Manually removed table.
Installed new version and uninstalled it to verify that table was properly removed.
From event log:
Close #392
> FIX: Uninstall fails when dropping table activeforums_Tags

- Dnn.CommunityForums/BuildScripts/ModulePackage.targets
We want to capture Illustrator source files into the repository but don't want to distribute as part of the install package.
- Add exclude to ModulePackage.targets
Did a build before/after exclusion and verified install .zip
Close #402
> Exclude illustrator logo/branding source files from build

- Dnn.CommunityForums/CustomControls/ServerControls/PagerNav.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
Incorrect links in pager when forum overrides (does not inherit) settings from forum group.
- changed to use common URL logic
Tested multiple forums and pages in test copy of dnncommunity.org
Close #425
> FIX: Incorrect links in pager when forum does not inherit group settings

- Dnn.CommunityForums/CustomControls/ServerControls/ForumLoader.cs
- Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/Services/ForumServiceController.cs
- Dnn.CommunityForums/Services/ModerationService.cs
- Dnn.CommunityForums/class/Email.cs
- Dnn.CommunityForums/class/ForumBase.cs
- Dnn.CommunityForums/class/ForumController.cs
- Dnn.CommunityForums/class/Subscriptions.cs
- Dnn.CommunityForums/class/TemplateUtils.cs
- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForums/components/Replies/Replies.cs
- Dnn.CommunityForums/components/Topics/TopicsController.cs
- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
- Dnn.CommunityForums/controls/af_modreport.ascx.cs
- Dnn.CommunityForums/controls/af_modtopics.ascx.cs
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/controls/af_quickreply.ascx.cs
- Dnn.CommunityForums/handlers/forumhelper.ashx.cs
Forum settings in Control Panel were reverting back to previous settings. 
In 08.00.00, where caches are now separated by moduleId to support separate caches for multiple installs of the Forums module. In the Control Panel, forum settings changes were being saved with module ID but lookups were not including the module id, so the caches were not synchronized.
- Change all forum get method calls to pass module id
- Refactor forum get methods 
Close #429
> FIX: Forum settings in Control Panel

- Dnn.CommunityForums/ReleaseNotes.txt
- Dnn.CommunityForums/class/ForumsConfig.cs
Correct an issue encountered related to #229 during 08.00.00 upgrade testing.
During an 8.0 install, a new themes/theme.css file gets installed.
However, if it's an upgrade, any existing themes/module.css gets renamed to theme.css.
Instead, leave the existing module.css, and document in release notes.
- don't rename themes/module.css to theme.css
- add note to release notes
Installed 07.00.12, and upgraded to 08.00.00. 
Verified that themes/module.css and themes/theme.css exist.
Close #441
> INSTALLER: Don't rename themes/module.css to theme.css

- Dnn.CommunityForums/controls/af_grid.ascx.cs
- Dnn.CommunityForums/controls/af_search.ascx.cs
Theme name duplicated in icon URLs resulting in 404 errors.
- remove duplicated theme name from URL
Close #437
> FIX: theme name duplicated in icon URL causing 404 on some pages

- Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
- Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
- Dnn.CommunityForums/class/ForumsConfig.cs
- Dnn.CommunityForums/class/Globals.cs
- Dnn.CommunityForums/class/Settings.cs
- Dnn.CommunityForums/class/TemplateCache.cs
- Dnn.CommunityForums/class/Templates.cs
- Dnn.CommunityForums/components/Common/ForumSettingsBase.cs
- Dnn.CommunityForums/components/Topics/TopicsController.cs
- Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Rename an existing "_default" theme to "_legacy"
- change upgrade code to rename folder
- sql code to change module setting if found
- Tested against copy of dnncommunity.org
- ensure that default templates are properly loaded during a new install
- ensure that existing templates are properly upgraded from 07.00.12
- ensure that template editor in control panel functions properly without HTML/text email templates
- ensure basic forums functionality (post topic/reply, etc.)
- ensure that email notifications are properly sent out with HTML templates
Close #462
> ENH: rename an existing "_default" theme to "_legacy"

- Dnn.CommunityForums/Classic.ascx.cs
- Dnn.CommunityForums/CustomControls/UserControls/Members.cs
- Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
- Dnn.CommunityForums/class/TemplateUtils.cs
- Dnn.CommunityForums/class/UserProfile.cs
- Dnn.CommunityForums/components/Users/UserController.cs
User signature remains cached after being changed in 'my settings'
- fixed incorrect cache key
- duplicated prior to changes
- tested after changes
Close #492
> FIX: Clear cached user signature when changed

- Dnn.CommunityForums/class/Email.cs
- Dnn.CommunityForums/class/TemplateCache.cs
- Dnn.CommunityForums/class/TemplateUtils.cs
- Dnn.CommunityForums/class/Templates.cs
- Dnn.CommunityForums/controls/admin_templates_edit.ascx.cs
- Dnn.CommunityForums/controls/af_modreport.ascx.cs
If module doesn't not have any templates defined, default templates should be used.
- Change template logic to load default template if nothing is specified in the database.
- Additional template loading refactoring
Tested against copy of @Timo-Breumelhof site as well as a small test site, upgraded from 07.00.12 to 08.00.00.
Before the changes, 'object reference' error:
After changes, topic loads properly:
Close #479
> FIX: if no templates loaded, default templates should still work

- Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Topic subscriptions should be moved with topic.
- change stored procedure `activeforums_Topics_Move` to move subscriptions when moving topic
- change stored procedure `activeforums_Subscriptions_IsSubscribed` to look at subscription based on topic without regard to forum (for backward compatibility)
1. subscrbed to topic
2. moved topic
3. subscription stayed
Close #537
> FIX: move subscriptions when moving topic

- Dnn.CommunityForums/class/Templates.cs
PR #527 updated template logic, but removed a couple lines that should not have been removed.
Specifically, the loading of the templates calls a stored procedure which returns multiple resultsets, and the "nextresult" method was removed. This PR restores the missing lines.
- restore missing lines.
Close #539
> FIX: restore removed code from #527

- Dnn.CommunityForums/Properties/AssemblyInfo.cs
- Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
- Dnn.CommunityForumsTests/Properties/AssemblyInfo.cs
After module renamed, unit test project stopped working.
- update InternalsVisibleTo attribute to correct name so that unit tests can see `internal` methods
- remove attribute related to Pex; not using since it requires higher VS edition
Close #542
> FIX: Build issues with unit test project after module was renamed

- Dnn.CommunityForums/08.00.00.txt
TASK: add DesktopModules/ActiveForums/images/ambuttonback.gif to 08.0……0.00.txt cleanup file
images/ambuttonback.gif removed in 08.00.00, and needs to be removed during upgrade since it doesn't get uninstalled.
- add DesktopModules/ActiveForums/images/ambuttonback.gif to 08.00.00.txt cleanup file 
On local install, install 07.00.12, upgrade to 08.00.00, uninstall 08.00.00 and verify file is removed.
Close #562
> TASK: remove images/ambuttonback.gif 

- Dnn.CommunityForums/config/defaultsetup.config
Delivered default theme now "community-default" rather than "community"
- update theme name in initial install
Close #
> Delivered default theme now "community-default" rather than "community"

- Dnn.CommunityForums/themes/community-default/.gitignore
- Dnn.CommunityForums/themes/community-default/custom/README.md
fix #598 
- Added the custom folder to the default template
- Added a readme.md to the folder
- 
locally
Close #
> ENH: Added Custom folder and readme.md  fixes #598

- Dnn.CommunityForums/config/templates/QuickReply.ascx
- Dnn.CommunityForums/sql/08.00.00.SqlDataProvider
Forums 08.00.000 adds template support for "quick reply" (PR # 436). When you upgrade from a previous version, existing templates are updated, but a quick reply template (and ability to select one) is not created. 
- Create quick reply template record(s) for existing Forums module instance(s) so they are properly upgraded
- Fix names on input tags in quick reply template html (unrelated but noticed they were incorrect)
local install. Install and configure 07.00.12, then upgrade to 08.00.00.
Template file created during upgrade and available for selection:
Close #617
> ENH: lmprove user experience when upgrading and then setting quick reply template 

- Dnn.CommunityForums/class/Injector.cs
- Dnn.CommunityForums/scripts/afcommon.js
Change collapsible icon to use chevron without circle
Local install. 
Old version:
New version:
> ENH: Use non-circle version of chevron for collapsible icon

- Dnn.CommunityForums/BuildScripts/ModulePackage.targets
I noticed that the install zip was quite large (6MB)
This was due to theDnn.CommunityForums\themes\community-default\node_modules folder getting included
Make sure the node_modules folder does not get zipped
Local install
Close #583
> fixes #583 Theme nodule_modules exclusing for installer ZIP

- Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx
- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.designer.cs
- Dnn.CommunityForums/controls/admin_templates_edit.ascx.cs
Adds hyperlink to parent forum/group in Control Panel forum editor
- Add hyperlink to control panel forum editor; and populate as appropriate
- New resource in ControlPanel.resx: `[RESX:Parent]`
Local install
Close #669
> ENH: Hyperlink to parent forum/group in Control Panel forum editor

- Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Incorrect results on 'most liked' page.  In the `activeforums_Likes` table, the column `PostId` is used to track likes. `PostId` needs to be JOINed to `ContentId` (not to `TopicId`) in `activeforums_Content`; also needs to reflect likes from replies.
- Updated `activeforums_UI_MostLiked` stored procedure 
Local install
Before:
After:
Close #666
> FIX: 'Most liked' incorrect results

- Dnn.CommunityForums/Controllers/TokenController.cs
- Dnn.CommunityForums/CustomControls/ServerControls/Callback.cs
- Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
- Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
- Dnn.CommunityForums/CustomControls/UserControls/WhatsNewRSS.cs
- Dnn.CommunityForums/CustomControls/Views/ForumDisplay.cs
- Dnn.CommunityForums/Deprecated/Utilities.cs
- Dnn.CommunityForums/Entities/TopicInfo.cs
- Dnn.CommunityForums/class/TemplateUtils.cs
- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForums/components/Data/ForumsDB.cs
- Dnn.CommunityForums/components/Helpers/Localization.cs
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/controls/af_search.ascx.cs
- Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs
- Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
- Dnn.CommunityForums/feeds.aspx.cs
- Dnn.CommunityForumsTests/class/UtilitiesTests.cs
- Use System.Web.HttpUtility's `HtmlEncode`/`HtmlDecode` & `UrlEncode`/`UrlDecode` methods consistently rather than using roll-your-own and/or relying on HttpContext.
-
Local install
Part of #264
> Refactoring: Use HttpUtility methods consistently

- Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
- Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
New UI elements for topic/forum subscriber counts were added in 8.0, but still needed to be added to the community-default theme.
Topic view:
- added link to group
- added subscriber count(s)
Topics view:
- added subscriber count(s)
> ENH: Added subscriber counts to topics / topic view in community-default theme

- Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Missing spaces in 08.01.00.SqlDataProvider causing installer error
- Corrected stored procedure
Local install and update from 07.00.12
> FIX: missing spaces in 08.01.00.SqlDataProvider causing installer error

- Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/scripts/afcommon.js
Subscribing not working when adding a new topic
- Change posting form to use server-side checkbox when adding a new topic
- Change JavaScript to not call subscribe API when adding a new topic
Local install; tested adding new topic and replying to existing topics
Close #697
> FIX: Can't subscribe when adding new topic

- Dnn.CommunityForums/ActiveForums.ascx.cs
- Dnn.CommunityForums/CustomControls/HTML/CategoryTreeView.cs
- Dnn.CommunityForums/CustomControls/HTML/ForumContentView.cs
- Dnn.CommunityForums/CustomControls/ServerControls/CategoryNavigator.cs
- Dnn.CommunityForums/CustomControls/ServerControls/ForumLoader.cs
- Dnn.CommunityForums/CustomControls/ServerControls/PagerNav.cs
- Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
- Dnn.CommunityForums/CustomControls/ServerControls/TopicsNavigator.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
- Dnn.CommunityForums/ForumSettings.ascx.cs
- Dnn.CommunityForums/Services/ForumAuthorizeAttribute.cs
- Dnn.CommunityForums/class/ForumBase.cs
- Dnn.CommunityForums/class/Globals.cs
- Dnn.CommunityForums/class/Permissions.cs
- Dnn.CommunityForums/class/SettingsBase.cs
- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForums/components/Controls/ControlUtils.cs
- Dnn.CommunityForums/components/Extensions/ReWriter.cs
- Dnn.CommunityForums/controls/af_grid.ascx.cs
- Dnn.CommunityForums/controls/af_modban.ascx.cs
- Dnn.CommunityForums/controls/af_modreport.ascx.cs
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/controls/af_search.ascx.cs
- Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs
- Dnn.CommunityForums/controls/af_searchquick.ascx.cs
- Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
- Dnn.CommunityForums/handlers/forumhelper.ashx.cs
Replace numerous hard-coded constants with centralized global constants.
Close #690
> TASK: Centralize string constants and use interpolation

- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
…in control panel; regression from PR #677
Fix mismatched query param for URL prefix when changing forum group in control panel; regression from PR #677 when separating group / forum inheritance for security and features
Local install.
Before:
whatever is in vanity name gets changed to 'false':
After:
correctly saved
> FIX: URL prefix (vanity name) not saved for Forum Group in Control Panel

- Dnn.CommunityForumsTests/DnnCommunityForumsTests.csproj
- Dnn.CommunityForumsTests/app.config
- Dnn.CommunityForumsTests/class/UtilitiesTests.cs
- Dnn.CommunityForumsTests/packages.config
Update Moq and NUnit versions to latest version to work with Visual Studio 2022 17.4+
- Add NUnit.Analyzers to migrate NUnit3 to NUnit4 for existing tests
- Update NUnit3TestAdapter 4.3.1 to 4.5.0
- Update NUnit 3.13.3 to 4.1.0
- Update NUnit3TestAdapter 4.3.1 to 4.5.0
- Update Moq 4.18.4 to 4.20.70
- Update Microsoft.CodeCoverage 17.4.1 to 17.9.0
- Update Microsoft.NET.Test.Sdk  17.4.1 to 17.9.0
- 
Prior to update, tests would not run 
Exceptions in output window:
```
NUnit Adapter 4.3.1.0: Test discovery starting
Exception System.TypeInitializationException, Exception thrown discovering tests in E:\source\repos\johnhenley\Dnn.CommunityForums\Dnn.CommunityForumsTests\bin\Debug\DotNetNuke.Modules.ActiveForumsTests.dll
Exception System.TypeInitializationException, Exception thrown …
```
> TASK: Update NUnit & Moq for Unit Test Project

- Dnn.CommunityForums/App_LocalResources/SharedResources.resx
- Dnn.CommunityForums/config/templates/ReplyEditor.ascx
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/themes/community-default/templates/ReplyEditor.ascx
Minor updates to topic/reply editor UI
- Couple of tweaks to topic/reply editor to show "editing existing" topics / replies
- ReplyEditor template referenced [RESX:ReplyToMessage] resource key rather than [RESX:ReplyToTopic]; corrected this in default template, and community-default template. Also added [RESX:ReplyToMessage] as a resource key for any existing templates to show it correctly.
- Removed extra [RESX:ReplyToTopic] in ReplyEditor templates; was in two different places
- Added string resources [RESX:EditingExistingTopic] and  [RESX:EditingExistingReply] 
Local install
Close #717
> ENH: Updates to topic/reply editor UI

- Dnn.CommunityForums/App_LocalResources/SharedResources.resx
- Dnn.CommunityForums/class/ForumsConfig.cs
- Dnn.CommunityForums/class/Globals.cs
- Dnn.CommunityForums/components/Topics/TopicsController.cs
- Dnn.CommunityForums/controls/af_modban.ascx.cs
- Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Notifications when banning user:
- Adds entry to admin log
- Sends notifications to forum moderators
- New core message notification type DCF-UserBanned
- New resource strings
- Send notifications when banning user
local install
Banning user:
Notifications sent:
Admin log:
Close #721
> ENH: Moderator notifications when banning user

- Dnn.CommunityForums/BuildScripts/ModulePackage.targets
With this fix custom.css files will not be overwritten any longer on upgrade
Exclude Themes\**\custom\*.css from install package
Local install
Close #729
> BUG: Exclude Themes\**\custom\*.css from install package

- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForums/components/Controls/ControlUtils.cs
Admin log indicating null value for portalSettings from search crawler.
Search crawler runs outside of UI, and internally the DNN navigation manager NavigateURL() API uses PortalController.GetCurrentSettings() if PortalSettings not passed; update to call NavigateURL() with PortalSettings
- added method to internal URL builder to accept PortalSettings
- changed URL builder logic to lookup and pass PortalSettings
Local install
Close #754
> FIX: null value for portalSettings from search crawler

- Dnn.CommunityForums/App_LocalResources/SharedResources.resx
- Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
- Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
- Dnn.CommunityForums/controls/af_quickreply.ascx.cs
- Dnn.CommunityForums/controls/af_subscribe.ascx.cs
- Dnn.CommunityForums/scripts/afcommon.js
- Dnn.CommunityForums/scripts/resx.js
Minor UI changes for topic/forum subscriptions
- Changes 'subscribe/unsubscribe' to simply be 'subscribe' as the checkbox itself is the state 
- When a user has "subscribe" user preference checked, hide topic/reply subscription option since user will always be subscribed.
Local install
Close #753
> ENH: changes to subscription options

- Dnn.CommunityForums/Entities/EmailNotificationQueueInfo.cs
- Dnn.CommunityForums/sql/08.01.00.SqlDataProvider
Change activeforums_EmailNotificationQueue Id (identity) column from int to bigint/long to prevent possible overflow
> Change activeforums_EmailNotificationQueue Id column from int to bigint/long

- Dnn.CommunityForums/ForumSettings.ascx.cs
- Dnn.CommunityForums/components/Common/ForumSettingsBase.cs
- Dnn.CommunityForums/components/Helpers/UpgradeModuleSettings.cs
- Dnn.CommunityForums/components/Topics/TopicsController.cs
Inserts missing security option for social group in module settings.
- Added upgrade code to insert missing option 
- remove TabModuleSettings for 4 settings saved to both TabModuleSettings and ModuleSettings 
Note: module can only be on one tab; we have issue #531 to explore import/export, and #485 (explore Settings repository) if we need to move some settings to TabModuleSettings, but for now there is no need to have them in both.
Local install w/ walking thru debugger
Close #774
> FIX: Insert missing security option for social group in module settings

- Dnn.CommunityForums/Entities/ForumInfo.cs
LastPostId is not updated in the database so needs to be a calculated property in the ForumInfo entity.
This was in the code prior to updating to use DAL2. 
- Change LastPostId to getter only and populate it
local install
See related issue #792 to remove LastPostId from the activeforums_Forums table since it is not needed.
> FIX: LastPostId needs to be a calculated property in the ForumInfo entity

- Dnn.CommunityForums/App_LocalResources/SharedResources.resx
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
Show login link on TopicView page if unauthenticated rather than "you are not authorized"
- If unauthenticated, show link with message to login
- Add string resource to SharedResources: [RESX:NotAuthorizedReplyPleaseLogin]: 
`Please <a href="{0}">login</a> to post a reply.` where {0} is replaced with Portal's login URL.
Local install 
Close #781
> ENH: Show login link on TopicView page if unauthenticated rather than "you are not authorized"

- Dnn.CommunityForums/Services/ModerationService.cs
Moderation actions initiated from an activity feed notification generated an error message.
- Add [HttpPost] to API methods
- use Module ID passed as part of the notification rather than ActiveModule.ModuleID
Local install
Close #798
> FIX: Issues with executing moderation actions from Activity Feed Notifications

- Dnn.CommunityForums/components/Topics/TopicsController.cs
FIX: Search results should be visible to unauthenticated users if security is set for 'View'
- Handle security for "all users" and "unauthenticated users" in search crawler
Local install
Close #808
> FIX: Search results should be visible to unauthenticated users

- Dnn.CommunityForums/controls/profile_mypreferences.ascx
- Dnn.CommunityForums/module.css
Search popup not overlaying content. 
- Add z-index to module.css
- Removed z-index from profile_mypreferences since now in module.css
Local install.
Before:
After:
Close #824
> FIX: Search Popup needs z-index

- Dnn.CommunityForums/Classic.ascx.cs
- Dnn.CommunityForums/Controllers/ReplyController.cs
- Dnn.CommunityForums/CustomControls/ServerControls/Toolbar.cs
- Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
- Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
- Dnn.CommunityForums/class/Globals.cs
- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Use locale/language as a parameter in content caching where appropriate.
This allows user to freely switch between languages/locales while using forums.
Local install 
Close #825
> ENH: Locale-specific caching

- Dnn.CommunityForums/CustomControls/UserControls/WhatsNewRSS.cs
- Dnn.CommunityForums/DnnCommunityForums.csproj
- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForums/feeds.aspx.cs
Community Forums was changed in 7.0 to store everything in UTC but display based on user's preferred time zone (see PR #130). However, the display logic used .NET Framework [`TimeZoneInfo.BaseUtcOffset`](https://learn.microsoft.com/en-us/dotnet/api/system.timezoneinfo.baseutcoffset), which doesn't account for Daylight Savings Time. Times displayed in Community Forums are always off during Daylight Savings Time. This has been corrected.
- Use [`TimeZoneInfo.GetUtcOffSet()`](https://learn.microsoft.com/en-us/dotnet/api/system.timezoneinfo.getutcoffset) to calculate the offset rather than using `BaseUtcOffSet`
Local install
Record stored in database in UTC
Dates are displayed using user's preferred time zone:
Before this change (uses `BaseUtcOffset` so using Eastern Standard Time)
After …
> FIX: Show times correctly for daylight savings time

- Dnn.CommunityForums/CustomControls/UserControls/SubmitForm.cs
- Dnn.CommunityForums/config/templates/TopicEditor.ascx
- Dnn.CommunityForums/themes/community-bootstrap/templates/TopicEditor.ascx
- Dnn.CommunityForums/themes/community-default/templates/TopicEditor.ascx
Extra whitespace is shown in topic editor when not using topic properties or topic/post icons.
This PR adds two new token pairs, updates shipping templates, and adds logic to reduce the whitespace
- Add tokens `[AF:UI:SECTION:POSTICONS]`, `[/AF:UI:SECTION:POSTICONS]`, `[AF:UI:SECTION:PROPERTIES]`, `[/AF:UI:SECTION:PROPERTIES]`
- Update TopicEditor.ascx templates in all themes shipped with Community Forums
- Add logic to remove sections when post icons or topic properties features are not used
Local install
Before:
After:
> ENH: Reduce whitespace when not using topic properties or post icons

- Dnn.CommunityForums/controls/profile_mysubscriptions.ascx
- Dnn.CommunityForums/controls/profile_mysubscriptions.ascx.designer.cs
FIX: Subscribe to all forums displaying resource key rather than text when you click on it
- Subscribe button unnecessarily inside an update panel and not translated after AJAX update
Local install
Close #859
> FIX: Subscribe to all forums displaying resource key rather than text when you click on it

- Dnn.CommunityForums/config/defaultsetup.config
Change default avatar size (250x250 rather than 50x50) for better resolution. 
Local install
Close #888
> ENH: Change default avatar size (250x250 rather than 50x50)

- Dnn.CommunityForums/module.css
In 08.00.00 release, module.css was cleaned up, and non-module-specific classes were moved to _legacy/theme.css. Two classes related to the poll graph need to remain in module.css--but can be overridden by a theme's CSS if desired.
- Add back CSS to module.css for polls
Local install
Close #890
> FIX: Show graphic in poll in Community themes

- Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.resx
- Dnn.CommunityForums/DnnCommunityForums.csproj
- Dnn.CommunityForums/config/templates/TopicsView.ascx
- Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
- Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
Replace hardcoded "Started by" with resource string to support localization
- Renamed (unused) "StartedHeader" resource to [RESX:StartedHeader] (consistency)
- Updated templates
Local install
Close #870
> FIX: Replace hardcoded "Started by" text with resource string

- Dnn.CommunityForums/CustomControls/HTML/TopicBrowser.cs
- Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
- Dnn.CommunityForums/DnnCommunityForums.csproj
- Dnn.CommunityForums/class/TemplateUtils.cs
- Dnn.CommunityForums/class/UserProfiles.cs
- Dnn.CommunityForums/class/UsersOnline.cs
- Dnn.CommunityForums/controls/af_grid.ascx.cs
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/controls/af_profile.ascx.cs
- Dnn.CommunityForums/controls/af_search.ascx.cs
- Dnn.CommunityForums/controls/af_sendto.ascx.cs
- Dnn.CommunityForums/feeds.aspx.cs
[DISPLAYNAME] not included in email notifications
- Refactored to always pass PortalSettings to GetUserDisplayName()
Local install
Before 8.1
After 8.1
This PR
Close #923
> FIX: [DISPLAYNAME] not included in email notifications

- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/Services/Controllers/ReplyController.cs
- Dnn.CommunityForums/Services/Controllers/TopicController.cs
Corrects issues with not being able to mark a reply as correct answer.
- Restore code (removed by a github merge) to ReplyController web api method 
- Only show 'mark as answer' on replies not original topic
- When check permissions for web api methods, convert UserInfo.Roles from names to IDs (IDs is used in PermissionController)
Local install
Close #945
> FIX: Can't mark reply as correct answer

- Dnn.CommunityForums/Controllers/ModerationController.cs
- Dnn.CommunityForums/controls/af_grid.ascx
- Dnn.CommunityForums/controls/af_search.ascx
Improve display of results in filtered topic views and search results
- During CSS modernization, CSS for these two views was moved to the _legacy theme but needs to remain until these views are overhauled in an upcoming version to be templated and use more modern HTML/CSS.
- In the meantime, the CSS for each of these views is restored within the .ascx page rather than load it from module.css or the CSS for a given theme. 
- In other words, this is a temporary fix awaiting a more permanent solution.
Local install
Close #948 
Close #949
> FIX: Alignment of results in filtered topics and search results

- Dnn.CommunityForums/Controllers/ModerationController.cs
- Dnn.CommunityForums/DnnCommunityForums.csproj
- Dnn.CommunityForums/DnnCommunityForums.dnn
- Dnn.CommunityForums/sql/08.01.01.SqlDataProvider
ENH: Exclude topics marked as "resolved" or "informative" from unanswered filtered topic view since those topics don't need to be answered.
- Updated `activeforums_UI_UnansweredView` to exclude topics with status 0 (Informative) or 3 (resolved)
Local install
Close #946
> ENH: Exclude topics marked as "resolved" or "informative" from unanswered filtered topic view

- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Expanding the cache key parameters in #944 caused exception when clearing that cache in the topic editor 
- Clear cache using broader cache key
Local install
Close #
> FIX: Expanded cache key added to handle paging causing exception when saving topic

- Dnn.CommunityForums/Controllers/ForumController.cs
- Dnn.CommunityForums/DnnCommunityForums.dnn
- Dnn.CommunityForums/DnnCommunityForums_Symbols.dnn
- Dnn.CommunityForums/Properties/AssemblyInfo.cs
- Dnn.CommunityForums/ReleaseNotes.txt
Clicking 'Save' in control panel on forum that is not inheriting group security restores default security
- Default permissions should not be applied unless 1) for a new forum or 2) switching from inheriting group security to not inheriting
Local install
Close #964
> FIX: Clicking 'Save' in control panel on forum that is not inheriting group security restores default security

- Dnn.CommunityForums/Controllers/ForumController.cs
- Dnn.CommunityForums/Controllers/ReplyController.cs
- Dnn.CommunityForums/Controllers/TopicController.cs
- Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
- Dnn.CommunityForums/components/Topics/TopicsController.cs
Forum icons not changing color when a new topic is added
- Last topic access date for user is in `activeforums_Forums_Tracking` which has yet been moved to DAL2 and the Forums View didn't have a correct/updated value; added a shim function to retrieve this value until table is used to DAL2 and permanent solution is implemented.
- Updating last forum updated date/topic, etc. was moved to processing queue, so doesn't get updated immediately; logic changed to update the last updated date/topic info for the forum when topic is being saved. Processing queue item will still process but shouldn't update again unless a new topic has appeared. Note: if viewing own topic, there is no concept of it being a "new topic" since you are the user who created it. You have to view it from a different user. …
> FIX: Forum icon not changing when new topic

- Dnn.CommunityForums/Controllers/PermissionController.cs
- Dnn.CommunityForums/WhatsNewOptions.ascx.cs
What's New should only show selected forums
- Fix forum filtering
- Fix exception when saving What's New module settings without selecting any forums
Local install
Close #992 
Close #993
> FIX: What's New should only show selected forums

- Dnn.CommunityForums/Controllers/TopicController.cs
- Dnn.CommunityForums/controls/af_post.ascx.cs
Correct update of post count for moderated content
- Move post count update to be after stored procedure is executed
- Remove unnecessary duplicated code
Local install
Before moderation:
(should be 2 not 1).
After moderation (correctly shows 3)
Close #983
> FIX: Correct update of post count for moderated content

- Dnn.CommunityForums/DnnCommunityForums.csproj
- Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
- Dnn.CommunityForums/sql/Uninstall.SqlDataProvider
Remove duplicated foreign keys; remove embedded "_activeforums_" from FK names
Close #898
> TASK: remove duplicated foreign keys; remove embedded "_activeforums_" from FK names

- Dnn.CommunityForums/Controllers/ForumController.cs
- Dnn.CommunityForums/Controllers/ForumGroupController.cs
- Dnn.CommunityForums/Controllers/PermissionController.cs
- Dnn.CommunityForums/Entities/ForumGroupInfo.cs
- Dnn.CommunityForums/Entities/ForumInfo.cs
FIX: default permissions not set correctly after ModuleId added to activeforums_Permissions in PR#1016
Local install
Close #726
> FIX: default permissions not set correctly after PR 1016

- Dnn.CommunityForums/Entities/TopicTrackingInfo.cs
- Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
`MaxTopicRead` and `MaxReplyRead` in `activeforums_Forum_Tracking` table not updated 
- update `activeforums_Topics_Tracking_UpdateUser` stored procedure to update `activeforums_Forum_Tracking`
- update existing data
- fix incorrect column mapping in `TopicTrackingInfo`
Local install
Before:
After:
Close #1032
> FIX: Correct forum tracking updates

- Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
FIX: Split errors after SQL updates to `activeforums_ForumTopics` in #1030
- When splitting a reply to its own topic, the reply is deleted. Need to remove and recalculated `LastReplyId` in `activeforums_ForumTopics` to avoid referential integrity violation
Local install; repeated splitting
Close #1037
> FIX: Split errors after SQL updates to activeforums_ForumTopics

- Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Update next/previous topic pointers without including (soft-)deleted topics
Local install
Close #1043
> FIX: Topics Prev/Next pointers should ignore deleted topics

- Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.resx
- Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
Add "Child" forum resource tokens
- Added [RESX:Child] and [RESX:of] resource strings
- Updates community default forum view template to include these as well as [FORUM:PARENTFORUMNAME] token (new in 8.2)
Local install as part of 8.2 development.
Close #470
> Add "Child" forum resource tokens

- Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.resx
- Dnn.CommunityForums/class/ForumBase.cs
- Dnn.CommunityForums/class/Settings.cs
Token replacement is getting an overhaul in 8.2, and "legacy" tokens in existing templates are being remapped to newer tokens either unique to Community Forums [FORUM:*], [FORUMTOPIC:*], [FORUMPOST:*], and [FORUMUSER:*]. Tokens that are generic to DNN are being remapped to their respective counterpart in DNN, e.g. [DISPLAYNAME] -> [USER:DISPLAYNAME].
To support legacy Community Forums users, the replacement of tokens in (customized) templates not shipped with the Forums module, the mapping/replacement will be logged for each token to the admin log. This requires adding new string resources.
This PR is one of many related to token replacement; the logic for using these new string resources will be in another PR.
Close #1061
> ENH: New message resources for token replacement 

- Dnn.CommunityForums/Controllers/ForumController.cs
- Dnn.CommunityForums/Controllers/ForumUserController.cs
- Dnn.CommunityForums/Controllers/ReplyController.cs
- Dnn.CommunityForums/CustomControls/HTML/TopicBrowser.cs
- Dnn.CommunityForums/CustomControls/Views/ForumDisplay.cs
- Dnn.CommunityForums/DnnCommunityForums.csproj
- Dnn.CommunityForums/Entities/AuthorInfo.cs
- Dnn.CommunityForums/Entities/ForumInfo.cs
- Dnn.CommunityForums/Entities/ForumTrackingInfo.cs
- Dnn.CommunityForums/Entities/ForumUserInfo.cs
- Dnn.CommunityForums/Entities/IPostInfo.cs
- Dnn.CommunityForums/Entities/ReplyInfo.cs
- Dnn.CommunityForums/Entities/TopicInfo.cs
- Dnn.CommunityForums/Entities/TopicTrackingInfo.cs
- Dnn.CommunityForums/Services/Tokens/ResourceStringTokenReplacer.cs
- Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
- Dnn.CommunityForums/class/Globals.cs
- Dnn.CommunityForums/class/TemplateUtils.cs
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/controls/af_quickreply.ascx.cs
Implements support for DNN core token replacement APIs
Centralizes token replacement within module
Another PR will actually implement and utilize the replacement logic in each "view" used by the Forums module.
- Implement IPropertyAccess for forum, forumuser, topic, reply, post
- Add token replacement and mapping from "legacy" tokens to new tokens and DNN standard tokens
- Adds a resource file for "legacy" token mapping that inject HTML markup (newer tokens do not inject markup) 
Close #1069
> ENH: Implements TokenReplace & IPropertyAccess for primary Forums entites

- Dnn.CommunityForums/ForumSettings.ascx.cs
- Dnn.CommunityForums/components/Helpers/UpgradeModuleSettings.cs
Upgrade code included in #1023 didn't completely cleanup old module setting "ForumConfig", which is used for Forums security metadata when used for social groups. This causes an exception when accessing module settings. 
- Updated upgrade code to remove old settings
- Detect anomalies and re-run upgrade code (this should only affect anyone who built 8.2 from this repo as a pre-released version (@Timo-Breumelhof ) and upgraded an existing site but leaving it in just in case).
Local install
Close #1078
> FIX: Exception loading module settings

- Dnn.CommunityForums/Controllers/ForumController.cs
- Dnn.CommunityForums/Services/Controllers/ForumController.cs
- Dnn.CommunityForums/class/ForumController.cs
- Dnn.CommunityForums/controls/af_quickjump.ascx.cs
- Dnn.CommunityForums/controls/af_searchadvanced.ascx.cs
- Dnn.CommunityForums/controls/htmlcontrols/movetopic.ascx
User should be able to move a topic to a hidden forum as long as they have access to that forum.
- Show hidden forums in move to forum list
- Change 'Save' button to 'Move'
Local install
Close #1089
> ENH: Enable move topic to hidden forum

- Dnn.CommunityForums/config/templates/ForumView.ascx
- Dnn.CommunityForums/config/templates/TopicsView.ascx
- Dnn.CommunityForums/module.css
- Dnn.CommunityForums/themes/_legacy-module.css
Prior versions had duplicated UI elements for topic / view / reply counts in forum and topics views. With theme/CSS improvements, these are no longer needed.
- remove "hidden stats" HTML elements
- remove CSS classes
Close #461
> TASK: Remove obsolete "hiddenstats"

- Dnn.CommunityForums/App_LocalResources/LegacyTokenResources.resx
- Dnn.CommunityForums/Controllers/EmailController.cs
- Dnn.CommunityForums/Controllers/ReplyController.cs
- Dnn.CommunityForums/Controllers/TopicController.cs
- Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
- Dnn.CommunityForums/Entities/ForumGroupInfo.cs
- Dnn.CommunityForums/Entities/ForumInfo.cs
- Dnn.CommunityForums/Entities/ForumUserInfo.cs
- Dnn.CommunityForums/Entities/ReplyInfo.cs
- Dnn.CommunityForums/Entities/TopicInfo.cs
- Dnn.CommunityForums/Services/ModerationService.cs
- Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
- Dnn.CommunityForums/class/Subscriptions.cs
- Dnn.CommunityForums/class/TemplateUtils.cs
- Dnn.CommunityForums/config/templates/SubscribedEmail.ascx
- Dnn.CommunityForums/controls/af_modtopics.ascx.cs
- Dnn.CommunityForums/themes/community-bootstrap/templates/ProfileInfo.ascx
- Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
- Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
- Dnn.CommunityForums/themes/community-default/templates/ProfileInfo.ascx
- Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
- Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
Modernizes token replacement for email notifications to use DNN API and entity-based IPropertyAccess
- Add some new properties to be (edit user link, private message, etc.)
- Add new legacy mappings
- Add new \[FORUMAUTHOR:\*\] token support to mirror [FORUMUSER:*] but in context of an author
- Add new \[FORUMAUTHORUSER:\*\] token support to mirror [USER:*] but in context of an author
- Add new \[FORUMAUTHORMEMBERSHIP:\*\] token support to mirror [MEMBERSHIP:*] but in context of an author
- Add new \[FORUMAUTHORPROFILE:\*\] token support to mirror [PROFILE:*] but in context of an author
- Prevent HTML tags in email subject (#1127)
Local install
Close #1127 
Close #1128
> ENH: Token replacement for email template

- Dnn.CommunityForums/App_LocalResources/LegacyTokenResources.resx
- Dnn.CommunityForums/Controllers/LikeController.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/Entities/IPostInfo.cs
- Dnn.CommunityForums/Entities/ReplyInfo.cs
- Dnn.CommunityForums/Entities/TopicInfo.cs
- Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
- Dnn.CommunityForums/scripts/afcommon.js
- Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
- Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
Use token replacement for like buttons
- Add tokens:
- `[FORUMPOST:LIKEONCLICK]` (inject UI code when like icon is clicked)
- `[FORUMPOST:ISLIKED]` (to inject content if topic is/is not liked by user)
- `[FORUMPOST:LIKECOUNT]` (to inject number of likes)
- Move HTML markup from C# code to delivered community templates
- Add legacy token mapping for `[LIKES], [LIKESx2], [LIKESx3]`
Local install
Close #1142
> ENH: Use token replacement for like buttons

- Dnn.CommunityForums/08.02.00.txt
- Dnn.CommunityForums/BuildScripts/ModulePackage.targets
- Dnn.CommunityForums/class/ForumsConfig.cs
- Dnn.CommunityForums/components/Topics/TopicsController.cs
In some old versions, SqlDataProvider files were installed to /sql/sql/ rather than just /sql/.
This PR moves the files, removes the /sql/sql/ folder, and logs to admin log.
Local install;
Close #247
> FIX: Move old /sql/sql/ files to /sql/

- Dnn.CommunityForums/Controllers/ForumController.cs
- Dnn.CommunityForums/Controllers/ForumGroupController.cs
- Dnn.CommunityForums/Providers/DataProviders/SqlDataProvider/SqlDataProvider.cs
- Dnn.CommunityForums/class/DataProvider.cs
- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
- Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Move some forum group table CRUD methods from stored procedures to use DAL2 controller/object
- Update code using sproc methods to use DAL2 controller/object
- Pass group settings key to `Groups_Save` rather than calculate it in stored procedure
- Mark for deprecation
- `Groups_Delete`
NOTE: Leaving `Groups_Save` for future.
local install
Close #1162
> TASK: replace forum group delete stored procedure with DAL2

- Dnn.CommunityForums/config/templates/ReplyEditor.ascx
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/themes/community-bootstrap/templates/ReplyEditor.ascx
- Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
- Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
Updates topic review when creating a reply to use new token replacement, and updates templates for supplied community themes.
local install
Close #1177
> ENH: token replacement for topic review when replying

- Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.fr-FR.resx
- Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.it-IT.resx
- Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.nl-NL.resx
- Dnn.CommunityForums/App_LocalResources/ControlPanel.ascx.resx
- Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.de-DE.resx
- Dnn.CommunityForums/App_LocalResources/Controlpanel.ascx.es-ES.resx
- Dnn.CommunityForums/ControlPanel.css
- Dnn.CommunityForums/Controllers/EmailController.cs
- Dnn.CommunityForums/Entities/FeatureSettings.cs
- Dnn.CommunityForums/class/ForumsConfig.cs
- Dnn.CommunityForums/class/Globals.cs
- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx
- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.designer.cs
Moves email notification subject template to forum control panel rather than from template database table, which will be removed in next major release. This allows email notifications to have specific subject lines if forums or groups override inherited settings.
local install
Close #702
> ENH: Move email notification subject template to forum settings

- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.de-DE.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.es-ES.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.fr-FR.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.it-IT.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.nl-NL.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.resx
- Dnn.CommunityForums/ForumSettings.ascx.cs
Two issues with social group security in module settings 
- Incorrect array size causing module settings to not be saved
- localized strings not populated for security options in forum settings
- correct array size and usage
- add missing string resources
Local install
Close #1185
> FIX: incorrect array size for social group security in module settings

- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.de-DE.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.es-ES.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.fr-FR.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.it-IT.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.nl-NL.resx
- Dnn.CommunityForums/App_LocalResources/ForumSettings.ascx.resx
- Dnn.CommunityForums/ForumSettings.ascx.cs
Continuation of PR #1186 
FIX: security option labels missing in module settings when configuring social group security
- resource strings need to be matching case in code and resx file
- Wrap in [RESX: ... ]
Local install
Close #1185
> FIX: security option labels missing in module settings for social group security

- Dnn.CommunityForums/themes/community-bootstrap/templates/TopicView.ascx
- Dnn.CommunityForums/themes/community-default/templates/TopicView.ascx
Forum post showing viewing user's signature not author's signature
- FIX: Use [FORUMAUTHOR:SIGNATURE] not [FORUMUSER:SIGNATURE] in delivered TopicView templates
Local install
Close #1194
> FIX: Wrong signature displayed in forum posts

- Dnn.CommunityForums/Controllers/ForumUserController.cs
- Dnn.CommunityForums/CustomControls/UserControls/UserProfile.cs
- Dnn.CommunityForums/Entities/ForumUserInfo.cs
- Dnn.CommunityForums/controls/profile_mypreferences.ascx.cs
- Dnn.CommunityForums/sql/08.02.00.SqlDataProvider
Fix issue found during pre-release testing where multiple records were being created for same user in `activeforums_UserProfiles`
- ForumUser needs to be saved correctly (primary key is ProfileId **not** UserId)
- Add SQL script to delete any duplicated users records, keeping only latest one (should not encounter this except anyone doing pre-release testing)
- Create index `[idx_activeforums_UserProfiles_Opt3]` with `**unique**` constraint
local install
Close #1218
> FIX: Multiple records created in activeforums_UserProfiles for same user

- Dnn.CommunityForums/Classic.ascx.cs
- Dnn.CommunityForums/Controllers/PermissionController.cs
- Dnn.CommunityForums/Entities/ReplyInfo.cs
- Dnn.CommunityForums/class/ForumsConfig.cs
- Dnn.CommunityForums/components/Topics/TopicsController.cs
Reverse some of PR #1221 changes for sorting permission set members (causing other issues)
Will revisit as part of #950 which will likely require major changes in this area.
Close #1161
> Sorting permission set members causing issues

- Dnn.CommunityForums/Controllers/ForumUserController.cs
- Dnn.CommunityForums/Entities/ForumUserInfo.cs
If a user doesn't have a value in CreatedOnDate in Users table, use minimum SQL date when creating the Forum User in activeforums_UserProfiles.
Local install
Close #1226
> FIX: Replace null CreatedOnDate with minimum SQL date when creating Forum User in activeforums_UserProfiles

- Dnn.CommunityForums/Controllers/ForumController.cs
- Dnn.CommunityForums/Controllers/PermissionController.cs
- Dnn.CommunityForums/ForumSettings.ascx.cs
Updates security settings when using social integration to use same permissions storage and security checking as standard forums.
(follow-on to PR #1230 & social integration testing).
Local install
Module settings for security when using social integration:
Permissions/Security now stored just like for other forums
Close #1229
> ENH: Save Social Integration forum security using common permissions

- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
- Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
- Dnn.CommunityForums/class/Settings.cs
- Dnn.CommunityForums/components/Controls/ControlUtils.cs
Fix email notifications
- Link in the notification was missing the scheme://hostname/
- Email subject was blank on upgraded forums module
- (unrelated) change [BODY] tokens in SEO metadata in TopicView and TopicsView to use [FORUMTOPIC:BODY] and [FORUM:FORUMDESCRIPTION] to skip legacy conversion and avoid unnecessary admin log alerts like this:
Local install:
Before:
After:
Close #1235
> FIX: Issues with email notifications

- Dnn.CommunityForums/DnnCommunityForums.csproj
- Dnn.CommunityForums/DnnCommunityForums.dnn
- Dnn.CommunityForums/sql/08.02.03.SqlDataProvider
Deleting replies causing 'error deleting post'. Investigation uncovered this error which is referential integrity issue:
The activeforums_Reply_Delete stored procedure was deleting from activeforums_Replies *before* setting activeforums_ForumTpics.LastReplyId (which points to record being deleted). When deleting a reply that is LastReplyId, throws exception. Re-order operations to set LastReplyId first before deleting reply.
- Change order of operations to set LastReplyId in activeforums_ForumTopics before deleting reply from activeforums_Replies
- Set lastreplyid to null not zero (zero not a valid value for foreign key)
Close #1242
> FIX: re-order operations when deleting replies 

- Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.resx
Unterminated token creating mangled markup for moderation notification
- fix tokens
Close #1252
> FIX: Unterminated token creating mangled markup 

- Dnn.CommunityForums/Controllers/ForumUserController.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/Entities/ForumUserInfo.cs
- Dnn.CommunityForums/controls/af_sendto.ascx.cs
- Dnn.CommunityForums/feeds.aspx.cs
After a reply is posted, the author of the topic is shown incorrectly (it shows the reply author not the topic author). 
This is due to topic object population/hydration in topic view and topic is cached with incorrect contentid. Once cache expires and topic is reloaded, topic is shown correctly. 
- Corrects the population of the topic object
Local install
Close #1254
> FIX: Incorrect author shown in filtered topics view immediately after a reply

- Dnn.CommunityForums/Controllers/ForumController.cs
- Dnn.CommunityForums/Entities/ForumInfo.cs
- Dnn.CommunityForums/controls/admin_manageforums_forumeditor.ascx.cs
- Dnn.CommunityForums/controls/admin_manageforums_home.ascx.cs
Fix some control panel issues related to forum/group administration.
- Restructure forum loading to loop through groups then forums for groups using DAL2 objects (previously, stored procedures return simple list with empty forum for an empty group). This allows groups without any forums to be properly maintained.
- Re-read forum to repopulate object after insert/update
- Set defaults for DateCreated/DateUpdated for forum
Local install
Close #1264
> FIX: Control Panel forum & group admin issues

- Dnn.CommunityForums/controls/af_quickreply.ascx.cs
FIX: Quick Reply replies requiring moderation should not go into process queue as approved messages
Local install
Close #1289
> FIX: Quick Reply replies requiring moderation

- Dnn.CommunityForums/Controllers/ForumUserController.cs
- Dnn.CommunityForums/Controllers/ModerationController.cs
- Dnn.CommunityForums/CustomControls/ServerControls/ForumContentNavigator.cs
- Dnn.CommunityForums/CustomControls/ServerControls/ForumContentTree.cs
- Dnn.CommunityForums/CustomControls/ServerControls/ForumNavigator.cs
- Dnn.CommunityForums/WhatsNew.ascx.cs
- Dnn.CommunityForums/class/SettingsBase.cs
- Dnn.CommunityForums/components/Users/UserController.cs
Moderation notifications were using a method that retrieves user from HttpContext. Use PortalSettings AdministratorId instead.
Also refactored a couple of other "get user from HttpContext" code instances.
Local install
Close #1290
> TASK: Don't look for user in HttpContext

- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForumsTests/class/UtilitiesTests.cs
New users (having null DateLastPost value) should pass flood control test.
Local install 
Also added new unit test for this.
Before:
After:
Close #1319
> FIX: Flood control preventing new user from posting

- Dnn.CommunityForums/CustomControls/ServerControls/QuickReply.cs
- Dnn.CommunityForums/Entities/ForumUserInfo.cs
- Dnn.CommunityForums/SimulateDateDiff.cs
- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForums/controls/af_post.ascx.cs
- Dnn.CommunityForums/controls/af_quickreply.ascx.cs
- Dnn.CommunityForumsTests/Services/Tokens/TokenReplacerTests.cs
- Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Removes reliance on 3rd-party code for 'SimulateDateDiff'
- Marked `SimulateDateDiff` class as obsolete; updated `DateDiff` method.
- Refactor flood and edit interval checks
- Updated `ambtnSubmit_Click` to use `this.ForumInfo.MainSettings.FloodInterval`.
- Changed `IsAuthenticated` in `ForumUserInfo.cs` to a computed property.
- Refactored `HasFloodIntervalPassed` to use `DateTime.UtcNow.Subtract(...)`.
- Introduced `HasEditIntervalPassed` method for edit interval checks.
- Updated `LoadTopic` and `LoadReply` methods to use the new edit interval check.
- Simplified flood interval check in `af_quickreply.ascx.cs`.
- Added new test cases for `HasFloodIntervalPassed` and `HasEditIntervalPassed` in `UtilitiesTests.cs`.
Local install and unit tests
Close #1286
> TASK: Remove 3rd-party SimulateDateDiff

- Dnn.CommunityForums/Entities/ForumGroupInfo.cs
- Dnn.CommunityForums/Entities/ForumInfo.cs
- Dnn.CommunityForums/Entities/LikeInfo.cs
- Dnn.CommunityForums/Entities/TopicInfo.cs
Replaced direct access to the TabId property with a call to the new GetTabId() method across multiple classes, including ForumGroupInfo, ForumInfo, LikeInfo, and TopicInfo. This change enhances encapsulation and maintainability. Updated URL constructions to consistently use GetTabId() for obtaining the TabId which permits the optional viewer module to show accurate URLs.
Close #1343
> TASK: Refactor TabId access when constructing URLs

- Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
FIX: Token replacement should not remove <br /> tags from content body
Local install
database content:
before change:
after change:
Close #1359
> FIX: Token replacement should not remove <br /> tags from content

- Dnn.CommunityForums/config/templates/ToolbarSearchPopup.ascx
Scope suppression of enter key to just the search box not entire page
Local install
Close #1360
> FIX: Allow Enter key in search box without interfering with other controls on page

- Dnn.CommunityForums/Controllers/PermissionController.cs
- Dnn.CommunityForums/Controllers/ReplyController.cs
- Dnn.CommunityForums/Controllers/TopicController.cs
- Dnn.CommunityForums/Controllers/UrlController.cs
- Dnn.CommunityForums/CustomControls/UserControls/ForumView.cs
- Dnn.CommunityForums/Entities/ForumGroupInfo.cs
- Dnn.CommunityForums/Entities/ForumInfo.cs
- Dnn.CommunityForums/Entities/ReplyInfo.cs
- Dnn.CommunityForums/Entities/TopicInfo.cs
- Dnn.CommunityForums/Services/Controllers/TopicController.cs
- Dnn.CommunityForums/Services/ModerationService.cs
- Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
- Dnn.CommunityForums/class/TemplateUtils.cs
Updates were made in #1344 to refactor TabId property for ForumInfo and ForumGroupInfo; however, these changes resulted in a StackOverflowException because a property was referencing a method which in turn referenced the property :(
- Update the TabId property and GetTabId() method in ForumInfo / ForumGroupInfo
Local install
Close #1343
> FIX: TabId property stackoverflow in ForumInfo/ForumGroupInfo

- Dnn.CommunityForums/CustomControls/UserControls/TopicView.cs
- Dnn.CommunityForums/CustomControls/UserControls/TopicsView.cs
- Dnn.CommunityForums/Entities/ReplyInfo.cs
- Dnn.CommunityForums/Entities/TopicInfo.cs
- Dnn.CommunityForums/Services/Tokens/TokenReplacer.cs
- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForums/controls/af_grid.ascx.cs
- Dnn.CommunityForums/controls/af_search.ascx.cs
Add bracket encoding/decoding to not interfere with token replacement
- Change `Utilities.EncodeBrackets` and `Utilities.DecodeBrackets` methods to internal rather than private. 
- Modify `GetProperty` method for topic & reply entities to encode brackets in content. 
- Modify `BindTopic` (topic view), `ParseTopics` (topics view), `TopicRepeaterOnItemDataBound` in `af_grid.ascx.cs` and `af_search.ascx.cs` to decode brackets after token replacement for correct display formatting.
Local install
Close #1384
> FIX: Add bracket encoding/decoding to not interfere with token replacement

- Dnn.CommunityForums/Controllers/PermissionController.cs
- Dnn.CommunityForums/CustomControls/UserControls/WhatsNewRSS.cs
- Dnn.CommunityForums/Entities/ForumGroupInfo.cs
- Dnn.CommunityForums/Entities/ForumInfo.cs
- Dnn.CommunityForums/WhatsNew.ascx.cs
- Dnn.CommunityForums/class/Utilities.cs
- Dnn.CommunityForumsTests/Controllers/PermissionControllerTests.cs
- Dnn.CommunityForumsTests/Entities/TopicItemTests.cs
- Dnn.CommunityForumsTests/Services/Tokens/TokenReplacerTests.cs
- Dnn.CommunityForumsTests/class/UtilitiesTests.cs
Fixes some minor issues encountered in pre-release testing, particularly
- HasEditIntervalPassed method in Utilities was not checking roleIds correctly (PR #1394)
- rewrote TabId handling for Forum and ForumGroup property accessors (PR #1344)
-  tweak some unit tests that weren't passing and needed more mock object initialization
- fix this issue with RSS/What's Next module
- Updated `ForumGroupInfo.cs` and `ForumInfo.cs` to use null-conditional operators and `HasValue` for safer property access.
- Enhanced permission checking logic in `Utilities.cs` for better clarity and maintainability.
- Modified test setups in `TopicItemTests.cs`, `TokenReplacerTests.cs`, and `UtilitiesTests.cs` to include additional properties for more comprehensive testing.
- Overall improvements to code safety, …
> FIX: HasEditIntervalPassed method issue  

- Dnn.CommunityForums/Classic.ascx.cs
- Dnn.CommunityForums/Controllers/ForumController.cs
- Dnn.CommunityForums/Controllers/PermissionController.cs
- Dnn.CommunityForums/DnnCommunityForums.dnn
- Dnn.CommunityForums/Entities/PermissionInfo.cs
- Dnn.CommunityForums/Services/AdminServiceController.cs
- Dnn.CommunityForums/class/Data/AttachmentsDB.cs
- Dnn.CommunityForums/class/ForumsConfig.cs
- Dnn.CommunityForums/class/Permissions.cs
- Dnn.CommunityForums/components/Topics/TopicsController.cs
- Dnn.CommunityForums/controls/admin_securitygrid.ascx
- Dnn.CommunityForums/controls/admin_securitygrid.ascx.cs
- Dnn.CommunityForumsTests/Controllers/PermissionControllerTests.cs
Upgrade permissions to just contain role ids
- Deprecated `ObjectType` and `Type` property from the `PermissionInfo` class (only 'Type' is now DNN roles).
- `DnnCommunityForums.dnn`: Added new upgrade version `09.00.00` to the `upgradeVersionsList`.
- Added upgrade code to transform existing `activeforums_Permissions` data
- `PermissionController.cs`: Removed `objectType` parameter from multiple methods and added new methods for handling role IDs.
- `ForumController.cs`: Modified `AddObjectToPermissions` calls to eliminate the `objectType` parameter.
- `admin_securitygrid.ascx`: Updated JavaScript functions to streamline security object management.
- Updated test cases in `PermissionControllerTests.cs` to reflect the removal of the `objectType` parameter.
Local install
Close #1393
> TASK: Upgrade permissions to contain just role ids

- Dnn.CommunityForums/App_LocalResources/SharedResources.de-DE.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.es-ES.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.fr-FR.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.it-IT.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.nl-NL.resx
- Dnn.CommunityForums/App_LocalResources/SharedResources.resx
- Dnn.CommunityForums/config/templates/SubscribedEmail.ascx
Moves hard-coded text from email notification template to resource files to facilitate localization.
Close #1454
> ENH: Move email notification text to resource files

- Dnn.CommunityForums/Entities/ForumInfo.cs
- Dnn.CommunityForums/sql/09.00.01.SqlDataProvider
Link for moderation page is missing in moderation notifications.
Unable to duplicate in local testing, but removing security checks when generating the link to determine if it is the security checks or the link creation that is at fault.
Close #1468
> FIX: Empty link in moderation notifications
